done again
NTHU-CP/NTHU-CPP pull request #102
Opened 2023-08-25 05:48 UTC by oohwee-yju

- [v] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [v] Rebase to the latest main branch.
- [v] List all the references.
- [v] Successfully build the website by mdBook with no error after the change.
- [v] Exclude any irrelevant files.
- [v] Link to the issue which is related to your change.
- [v] Review the content by myself.
- [v] Pass tests/CI.

2023-09-10 16:26 UTC, oohwee-yju commented
no, this is final version

2023-09-12 15:21 UTC, harry900831 requested changes
- It seems that the content isn't correctly rendered on mdBook
- I may merge this after you revise it, please scan through the whole article and check whether there's any typo or error.

2023-09-12 15:21 UTC, harry900831 commented on src/misc/interactive.md
> +
It seems that the contend isn't correctly be rendered on mdBook. 
Please revise it.

2023-09-12 15:21 UTC, harry900831 commented on src/misc/interactive.md
> +> Jury 有一組大小為 \\(k\\) 的集合，集合內的元素為 \\(1 \sim n\\) 且不重複的數字。> Jury 會將 \\(k\\) 跟 \\(n\\) 告訴 Participant。> Participant 可以問 Jury 的問題是：給兩個數字 \\(x, y\\)，Jury 將會在它的集合中找到跟 \\(x\\) 最接近的數字 \\(a\\)、跟 \\(y\\) 最接近的
You should insert a blank line between the tile and the content

2023-09-12 15:21 UTC, harry900831 commented on src/misc/interactive.md
Would you like to share the ppt that you teach before?
As a reference or put it at the beginning

2023-09-12 15:22 UTC, harry900831 commented on src/misc/interactive.md
> +
Render error not only on this part, please check the whole article.

2023-09-17 11:22 UTC, oohwee-yju commented
Problems should be fixed.
But I would like to keep the ppt private.

2023-09-17 19:07 UTC, harry900831 commented
I'll merge it after you fix the last issue

2023-09-20 12:28 UTC, oohwee-yju commented
I didn't found any typo.

2023-09-22 12:46 UTC, harry900831 requested changes

2023-09-22 12:48 UTC, harry900831 commented
It's seems that my review last week isn't out there so you didn't see it. I'll merge it and fix it by myself. Thanks

2023-09-22 12:48 UTC, merged