Add math intro
NTHU-CP/NTHU-CPP pull request #19
Opened 2023-02-05 10:24 UTC by PolarisChiba

2023-02-05 16:07 UTC, harry900831 requested changes

2023-02-05 16:07 UTC, harry900831 commented on src/math/math_intro.md
> +因此做為基礎，只要學好高中數學，再輔以一些競程的知識，其實就能夠有效解決諸多競程中的數學問題了。
感覺需要強調一下 可能可以粗體 會是 匡起來

2023-02-05 16:07 UTC, harry900831 commented on src/math/math_intro.md
> +也有者口口聲聲說不碰數學的選手拿到 ICPC 桃園站銀牌。
我認為數學並非必要的有點怪
口口聲聲不碰數學拿到 ICPC 桃猿戰銀牌也很怪
他具備基礎數學的能力 這有點誤導人

2023-02-05 16:07 UTC, harry900831 commented on src/math/math_intro.md
> +但最終，要推倒高牆，就只能主動碰觸高牆。
其實我原本預期這一頁的重點內容是 學習資源以及幾個需要知道的 key word

最後加上一個 學習資源的 section 

##Resources
放一下一些 online 學習資源
例如 [cp-algorithm - Algebra](https://cp-algorithms.com/#navigation)
或他有關數論的[算法筆記](https://zhuanlan.zhihu.com/p/105467597)

2023-02-05 16:07 UTC, harry900831 commented on src/SUMMARY.md
> +- [Mathematics](math/math_intro.md)
intro.md

2023-02-05 19:36 UTC, PolarisChiba commented on src/math/math_intro.md
> +# 數學
個人習慣這樣，如果你覺得改成段落比較好的話也行。

2023-02-05 19:37 UTC, PolarisChiba commented on src/math/math_intro.md
> +但最終，要推倒高牆，就只能主動碰觸高牆。
你預期這樣的話那要先講啊 QQ

2023-02-05 19:48 UTC, PolarisChiba commented on src/math/math_intro.md
> +# 數學
done

2023-02-05 19:48 UTC, PolarisChiba commented on src/math/math_intro.md
> +因此上述分類就做個參考即可。
done

2023-02-05 19:48 UTC, PolarisChiba commented on src/math/math_intro.md
> +因此做為基礎，只要學好高中數學，再輔以一些競程的知識，其實就能夠有效解決諸多競程中的數學問題了。
done

2023-02-05 19:48 UTC, PolarisChiba commented on src/SUMMARY.md
> +- [Mathematics](math/math_intro.md)
done

2023-02-06 07:51 UTC, harry900831 approved these changes

2023-02-06 07:51 UTC, harry900831 commented on src/math/math_intro.md
> +但最終，要推倒高牆，就只能主動碰觸高牆。
我有R 我一開始打給你的就有這樣寫

2023-02-06 07:53 UTC, PolarisChiba commented on src/math/math_intro.md
> +但最終，要推倒高牆，就只能主動碰觸高牆。
抱歉忘記了 QQ

2023-02-06 08:10 UTC, harry900831 requested changes

2023-02-06 08:10 UTC, harry900831 commented on src/math/intro.md
> +# 數學
Mathematics

至少這個和側邊標題相同

2023-02-06 08:10 UTC, harry900831 commented on src/math/intro.md
> +略~~（請有心力的人寫這一塊，感謝）~~
改成 待補

2023-02-06 09:01 UTC, merged