Split du's seive from arithmetic funciton to new chapter, modify typo…
NTHU-CP/NTHU-CPP pull request #23
Opened 2023-02-10 13:53 UTC by PolarisChiba

… in linear sieve

2023-02-20 08:50 UTC, harry900831 commented
You may split modify typo and add du's seive chapter to different commit or even different PR.

2023-02-20 08:54 UTC, harry900831 requested changes

2023-02-20 08:54 UTC, harry900831 commented on src/math/du_seive.md
> +    cin >> n;
wrong indention

2023-02-20 08:54 UTC, harry900831 commented on src/math/du_seive.md
> +typedef long long ll;
using ll = long long;

2023-02-20 08:54 UTC, harry900831 commented on src/math/du_seive.md
> +    for (int i = 2; i < lim; ++ i) {
wrong indention

2023-02-20 08:54 UTC, harry900831 commented on src/math/du_seive.md
> +（以上程式碼皆未在任何 OJ 上測試過，因此可能有著潛在 BUG，而且也沒有壓好常數。）
可以找一下哪裡可以 submit 測一下你的code嗎？
否則讀者看到這邊 也沒有真的有 OJ 可以練習

2023-02-20 08:54 UTC, harry900831 commented on src/math/du_seive.md
> +# 杜教篩
有太多 縮排沒縮好的Code

建議使用 clang-format 排好版

2023-02-21 13:16 UTC, PolarisChiba commented on src/math/du_seive.md
> +（以上程式碼皆未在任何 OJ 上測試過，因此可能有著潛在 BUG，而且也沒有壓好常數。）
沒有 OJ，都是假的。

2023-02-21 17:49 UTC, harry900831 commented on src/math/du_seive.md
> +（以上程式碼皆未在任何 OJ 上測試過，因此可能有著潛在 BUG，而且也沒有壓好常數。）
https://www.luogu.com.cn/problem/P4213

不要 resolve 還沒解決的 comment

2023-02-21 17:51 UTC, harry900831 commented on src/math/du_seive.md
> +（以上程式碼皆未在任何 OJ 上測試過，因此可能有著潛在 BUG，而且也沒有壓好常數。）
https://blog.csdn.net/skywalkert/article/details/50500009

2023-02-21 17:52 UTC, harry900831 commented
先額外發一格 PR 修正 typo  `if (i * p > n) break;`
我先 merge 那部分

2023-02-21 17:56 UTC, harry900831 requested changes

2023-02-21 17:56 UTC, harry900831 commented on src/math/du_sieve.md
> +~~這題一下子就變得好難QQ~~
Any references?

2023-02-21 17:56 UTC, harry900831 commented on src/math/du_sieve.md
> +>  求\\( \displaystyle S(n)=\sum_{i=1}^n \sum_{j=1}^n ij\times \gcd(i,j) \\) 的值。（\\( n\le 10^{10} \\)）
At least give us a hint.

2023-02-21 17:56 UTC, harry900831 commented on src/math/du_sieve.md
> +（實作略）
略過不用特別寫出來

但如果是希望能放的，放個 TODO 在這邊

2023-02-21 17:56 UTC, harry900831 commented on src/math/du_sieve.md
> +（以上程式碼皆未在任何 OJ 上測試過，因此可能有著潛在 BUG，而且也沒有壓好常數。）
:)

2023-02-21 17:57 UTC, PolarisChiba commented on src/math/du_seive.md
> +（以上程式碼皆未在任何 OJ 上測試過，因此可能有著潛在 BUG，而且也沒有壓好常數。）
不要，這些地方我不熟，我不寫我不熟或不確定的東西。

2023-02-21 17:59 UTC, harry900831 requested changes

2023-02-21 17:59 UTC, harry900831 commented on src/SUMMARY.md
>  	- [Arithmetic Function](math/arithmetic_function.md)
這裡要改成 兩個空白 不然我無法使用 mdbook 顯示

2023-02-21 18:00 UTC, harry900831 commented on src/math/du_seive.md
> +（以上程式碼皆未在任何 OJ 上測試過，因此可能有著潛在 BUG，而且也沒有壓好常數。）
我只是提供你題目

2023-02-21 18:13 UTC, PolarisChiba commented on src/math/du_sieve.md
> +~~這題一下子就變得好難QQ~~
我沒有。

2023-02-21 18:13 UTC, PolarisChiba commented on src/math/du_sieve.md
> +~~這題一下子就變得好難QQ~~
我認為就權當式子堆導的練習就好。

2023-02-24 11:28 UTC, harry900831 requested changes

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +# 數論分塊（整除分塊）
arithmetic decomposition looks weird to me.

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +舉例來說：\\( n=10 \\) 的情況下，\\( 7 \\) 所在的塊的右端點是 \\( \lfloor 10/\lfloor10/7\rfloor\rfloor=\lfloor10/1\rfloor=10 \\)。
use \frac for all \lfloor x/\lfloory/z\rfloor\rfloor

Please fix all the followings.

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +# 數論分塊（整除分塊）
https://codeforces.com/blog/entry/53925
https://en.wikipedia.org/wiki/Divisor_summatory_function

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +* [Codeforces 1780 E](https://codeforces.cc/contest/1780/problem/E)
Could you provide some hint or tag for these problem?

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +## 例題
Please revise your title hierarchy. It looks weird to me now.

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +因此時間複雜度從 \\(O(n)\\) 降為 \\(O(\sqrt{n})\\)。
https://math.stackexchange.com/questions/487401/sum-of-floor-of-harmonic-progression-sum-i-1n-lfloor-frac-ni-rfloor-2-sum

Consider adding this solution too

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +# 數論分塊（整除分塊）
I didn't find any proper English title for this chapter, maybe call it 數論分塊 or 整除分塊 (I prefer 整除分塊)

2023-02-24 11:28 UTC, harry900831 commented on src/math/arithmetic_decomposition.md
> +## 例題
maybe:

# 整除分塊

## introduction
### problem
### right end point

## application for 整除分塊
### 捲積的前綴和
### 複合數論分塊
## Exercises

2023-02-24 11:29 UTC, harry900831 commented
I will probably merge this first after this revision.

2023-02-24 13:19 UTC, PolarisChiba commented on src/math/arithmetic_decomposition.md
> +因此時間複雜度從 \\(O(n)\\) 降為 \\(O(\sqrt{n})\\)。
it seems unpractical to me.

2023-02-24 13:21 UTC, PolarisChiba commented on src/math/arithmetic_decomposition.md
> +* [Codeforces 1780 E](https://codeforces.cc/contest/1780/problem/E)
no

2023-02-24 13:21 UTC, PolarisChiba commented on src/math/arithmetic_decomposition.md
> +* [Codeforces 1780 E](https://codeforces.cc/contest/1780/problem/E)
the first three are too basic.
I can't solve the last one.

2023-02-25 17:29 UTC, harry900831 requested changes

2023-02-25 18:06 UTC, harry900831 approved these changes

2023-02-25 18:08 UTC, merged