Split linear sieve from arithmetic_functoin.md
NTHU-CP/NTHU-CPP pull request #31
Opened 2023-02-23 17:29 UTC by PolarisChiba

2023-03-02 17:35 UTC, harry900831 commented
Please resolve the above comments first.

2023-03-09 07:47 UTC, harry900831 commented
@PolarisChiba You hasn't resolved the comment.

2023-03-09 14:52 UTC, harry900831 requested changes

2023-03-09 14:58 UTC, PolarisChiba commented on src/math/linear_sieve.md
> +## 數論函數篩法
I tend to put it under arithmetic function now and maybe move it under "Seive" chapter if there is one in the future

2023-03-09 14:59 UTC, PolarisChiba commented on src/math/linear_sieve.md
> +# 線性篩
I plan to do it in the future.

2023-03-09 15:00 UTC, harry900831 commented
Add linear sieve to SUMMAYR
-> SUMMARY

2023-03-09 15:20 UTC, harry900831 requested changes

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +```
Make this a function.
Declare notPrime and primes as a vector

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +對於並非最小的質數 \\( p_2 \\)，當 \\( i = \frac{x}{p_2} \\) 的時候，因為 \\( i\mod p_2 = 0 \\)，因此會提早 ``break``。
use /bmod instead of /mod

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +> 所有質數的 ``notPrime`` 值都會是 ``false``。
改成以下可能比較通順：
對於所有質數 i， 經過上述計算後，notPrime[i] 等於 false。

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +> 所有合數的 ``notPrime`` 值都會是 ``true``。
Ditto

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +對於並非最小的質數 \\( p_2 \\)，當 \\( i = \frac{x}{p_2} \\) 的時候，因為 \\( i\mod p_2 = 0 \\)，因此會提早 ``break``。
這證明怪怪的吧？

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +```
Ditto, make it a function.

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +一般而言，給定函數 \\( f \\)要求 \\( f(n) \\)，假設 \\( p \\) 是 \\( n \\) 的最小質因數。
need a space after \\( f \\)

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +```
Ditto

2023-03-09 15:20 UTC, harry900831 commented on src/math/linear_sieve.md
> +```
Ditto

2023-03-09 15:21 UTC, harry900831 commented on src/math/linear_sieve.md
> +對於並非最小的質數 \\( p_2 \\)，當 \\( i = \frac{x}{p_2} \\) 的時候，因為 \\( i\mod p_2 = 0 \\)，因此會提早 ``break``。
https://math.meta.stackexchange.com/questions/20988/modulo-operator-rendering-poorly

2023-03-09 16:30 UTC, harry900831 requested changes

2023-03-09 16:30 UTC, harry900831 commented on src/math/linear_sieve.md
> +  vector<int> notPrime(n + 1, false);
vector\<bool\>

2023-03-09 16:30 UTC, harry900831 commented on src/math/linear_sieve.md
> +> 所有合數的 ``notPrime`` 值都會是 ``true``。
You didn't change this

2023-03-09 16:30 UTC, harry900831 commented on src/math/linear_sieve.md
> +特別注意到第三個情況也可以視作第一、二情況的 Otherwise。
Need more explanation

2023-03-09 16:30 UTC, harry900831 commented on src/math/linear_sieve.md
> +## 附註
Summary

2023-03-11 05:52 UTC, harry900831 approved these changes

2023-03-11 05:53 UTC, merged