Add #52 CDQ and Parallel Binary Search
NTHU-CP/NTHU-CPP pull request #63
Opened 2023-05-13 20:09 UTC by chyyen

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [x] Rebase to the latest main branch.
- [ ] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-06-12 16:35 UTC, harry900831 requested changes
Please re-request review after your revision.

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/CDQ.md
> +在分治時，先去算左區間詢問的答案，再將右區間的詢問以及左區間的新增操作按照 x 座標排序，這樣一來就可以用掃描線 + 一維資結去計算左區間的新增操作對右區間詢問的貢獻了。
分治了什麼？
什麼叫做左區間？

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/CDQ.md
> +>求 LCIS (longest common increasing subsequence)。
這例題我覺得不夠好

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/CDQ.md
> +> * 詢問某個區間中有多少不同的值
請提供OJ

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/CDQ.md
> +## 其他例題
我認為你還需要再詳細的講一題CDQ分治的題目

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/CDQ.md
> +## Reference
可以提供一下這些references 中哪個講得不錯 讀者有興趣可以去看

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +這時候我們就會用到整體二分這個技巧去一次處理多個詢問。
就可以用

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +\
這個敘述怪怪的
如果 Q 筆詢問每一筆都可以用 二分搜來找到
那時間複雜度是 O(QlogN)
你用整體二分時間複雜度一樣也是 O(QlogN)

但多筆詢問同時一起二分搜 可以重複利用一些每個二分搜會需要用到的資訊 才能達到更好的效果

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +如果我們對於每筆詢問分別去二分搜，時間複雜度大概會是 \\( O(nq\log n) \\) ，很明顯會 TLE ，因此我們考慮用整體二分。
how and why?

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +( 如果查詢出來的區間和 \\( \geq k \\) ，則答案 \\( \leq mid \\) ，反之則答案 \\( > mid\\) )
Need more explanation

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +Sample Code :
what's the time complexity?

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +至於原數列可以視為只有「更新新的貢獻」的修改，並且存在其他修改和詢問的最前面。
what's the time complexity

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +至於原數列可以視為只有「更新新的貢獻」的修改，並且存在其他修改和詢問的最前面。
請提供OJ
找不到的話 可以找類似的題目但是要用到一樣的技巧

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +至於原數列可以視為只有「更新新的貢獻」的修改，並且存在其他修改和詢問的最前面。
Need more explanation, 我一樣看不太懂

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +不過注意到由於整體二分是離線算法，所以計算 dp 時不能與前面的 dp 狀態有關。
如果還是要放的話 請提供例題，並針對例題使用此優化方式

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +> * \\( n, m, k \leq 3 * 10^5 \\)
\times

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +> [CSES Houses and Schools](https://cses.fi/problemset/task/2087)
可以將此題往上移
使用f(i, j) 取代dp[i][j]

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +```
再講解一提感覺比較好
可以把底下的 meteor 往上拉到這裡

2023-06-12 16:35 UTC, harry900831 commented on src/SUMMARY.md
> +- [Offline]()
There may be some problem while rendering the side bar, please ignore it, it's the bug from mdBook.

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +## 練習
有其他更常用的OJ的例題嗎？

2023-06-12 16:35 UTC, harry900831 commented on src/Offline/ParallelBinarySearch.md
> +## Reference
References

2023-06-16 19:11 UTC, harry900831 commented on src/Offline/CDQ.md
> +### 斜率優化
https://github.com/NTHU-CP/NTHU-CPP/pull/74#discussion_r1232634594

2023-06-16 19:15 UTC, harry900831 commented on src/Offline/CDQ.md
> +> \\( p_i \prec p_j \equiv (p_{i, 1} \lesseqgtr p_{j, 1}) \land (p_{i, 2} \lesseqgtr p_{j, 2}) \ ... \land \ (p_{i, d} \lesseqgtr p_{j, d}) \\)
看起來 CDQ 分治與普通分治的差別是子問題 [l, m) 內的元素會影響 [m + 1, r) 的答案

2023-06-23 14:13 UTC, chyyen commented
Ready for review @harry900831

2023-07-21 15:58 UTC, harry900831 requested changes
- Please resolve the comment by yourself after you fix it. If you want to discuss about it, just directly comment on it.
- Please make your explanation more clear. Imagine you are giving a lecture, I believe drawing dome figure would help the explanation.
- You may refer to others PR or the article that has been merged into NTHU-CPP to know that what kind of article you have to write.
  - https://nthu-cp.github.io/NTHU-CPP/graph/lca.html
  - https://nthu-cp.github.io/NTHU-CPP/math/introduction_to_generating_function.html
  - https://nthu-cp.github.io/NTHU-CPP/graph/introduction_to_AP_bridge.html
  - https://nthu-cp.github.io/NTHU-CPP/graph/introduction_to_BCC.html
  - https://nthu-cp.github.io/NTHU-CPP/greedy/basic.html
  - https://nthu-cp.github.io/NTHU-CPP/sqrt/sqrt_decomposition.html
- Please follow the format above too
- Please fix markdownlint and textlint.
- There should be two section
    1. Example problem: you should explain the problem in detail (including problem description, solution, code, time complexity/correctness analysis...). Also, please solve these problem with your own template code that mention above.
    2. Exercise problem: a problem list that reader may do if they want to practice treap, you don't have to explain these problem in detail, you may provide hint only.
- In my opinion, the article right now can't present that you have done a deep research on these topic. It looks like a zh-TW version of some post from CSDN blog.
- Please revise the sentence and the format. The layout could be better. Please try to use less but clear sentence to convey your idea. Please don't be limited by my comment, reorganize the whole article.
- You have to put more effort on this to get a great work. If the workload is too much, you may revise and merge the CDQ D&Q first.
- Please make your code short and clean, and use the formatter such as clang-format. Please prevent from useless comment on the code.
- Please read more online resources and do more problem about these topic.
- If you have no idea about how to enhance the quality of your article, just arrange a meeting with me on DC. We can discuss about it directly.

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +跟原來分治不太相同的點是，一般的分治將原問題分解成數個子問題後，每個子問題間的答案獨立。而 CDQ 分治中，則是分割出兩個子問題，且前面的子問題通常會影響到後面子問題的答案。
不需要使用 \

好好分段一下

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +就像前面說的，逆序數對就是其中一個二維偏序的例子，因為太過經典所以這邊就不做過多的解釋了，詳細的部分可以參考 [這份講義](https://drive.google.com/file/d/1SxuBzDDbgmpo2j2PyXEQ2Oe8BgVqM_DH/view) 。
可以refer 到https://github.com/NTHU-CP/NTHU-CPP/pull/66

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +```
可以不用付上code

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +> [原題連結](https://zerojudge.tw/ShowProblem?problemid=c571)
有沒有除了 zerojudge 之外更好的 problem source 啊？

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +> * \\( N \leq 10^5 \\)
missing size of a_i, b_i, c_i

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +
這部分需要更詳細的說明

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +
因為了保證？

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +
也有可能等於啊

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +除此之外還要避免掉 \\( a_i = a_j \\) 的狀況，因此一開始在排序時若 \\( a_i = a_j \\)，則依照 \\( b \\) 由大到小排，這樣就可以保證相同 \\( a_i = a_j, \ b_i < b_j \\) 的數對不會被算到了。
解釋也不夠清楚

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> ++ 動態問題轉為靜態問題 (操作分治)
還有斜率優化？

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +}
please provide code for BIT. 

If BIT.clear() over takes O(n) then the time complexity is incorrect.

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +除此之外還要避免掉 \\( a_i = a_j \\) 的狀況，因此一開始在排序時若 \\( a_i = a_j \\)，則依照 \\( b \\) 由大到小排，這樣就可以保證相同 \\( a_i = a_j, \ b_i < b_j \\) 的數對不會被算到了。
合併答案或計算左半區間對右半區間的影響 這部分需要加強說明

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +	}
Is this necessary? since you use lambda to sort at the main function

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +我們可以對第一維 sort，套 \\( D - 2 \\) 層 CDQ，再用資結去解決最後一維，或者直接套 \\( D - 1 \\) 層 CDQ。
資結 請註明是處理一為資料的結構 例如 BIT or 線段數
事實上我們也可以套 D-3 層 CDQ 然後使用 2 維線段數

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +```
看不懂這一 section 的目的與內容是啥

要帶題目的話也先講清楚 題目format?

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +這樣一來整體的時間複雜度為 \\( O(q\log^2 q) \\)，跟使用二維線段樹的複雜度一樣。
solution code?

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +> * 詢問在以 \\( (x_1, y_1) \\) 做為左下角並以 \\( (x_2, y_2) \\) 做為右上角的矩形內的值總和
應該有在長用的oj 有使用到這技巧的吧？
可以使用那些題目當 example

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +> * 詢問在以 \\( (x_1, y_1) \\) 做為左下角並以 \\( (x_2, y_2) \\) 做為右上角的矩形內的值總和
除非真的找不到好的考點的 才使用落谷

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +> [題目連結](https://www.luogu.com.cn/problem/P3157)
怎麼又是落谷

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +> \\( 1 \leq n, q \leq 10^5,\ 1 \leq a_i \leq 10^9 \\)
oj?

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +> [原題連結](https://www.luogu.com.cn/problem/P4690)
請參考其他篇文章的題目 format
需要把 problem source 的名稱放在連結上

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +* [https://www.cs.princeton.edu/~danqic/papers/divide-and-conquer.pdf](https://www.cs.princeton.edu/~danqic/papers/divide-and-conquer.pdf) ( CDQ 分治也可以在斜率優化時將動態凸包轉為靜態的，有興趣可以看這篇 )
Please read more references.

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +* [https://www.cs.princeton.edu/~danqic/papers/divide-and-conquer.pdf](https://www.cs.princeton.edu/~danqic/papers/divide-and-conquer.pdf) ( CDQ 分治也可以在斜率優化時將動態凸包轉為靜態的，有興趣可以看這篇 )
The more you read the better you write.

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> +* [https://www.cs.princeton.edu/~danqic/papers/divide-and-conquer.pdf](https://www.cs.princeton.edu/~danqic/papers/divide-and-conquer.pdf) ( CDQ 分治也可以在斜率優化時將動態凸包轉為靜態的，有興趣可以看這篇 )
Please prevent from reading article from oi-wiki, csdn blog only.

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +這時候我們就可以一次去處理多個詢問，透過重複每次檢查時會用到的資訊，來加速程式，也就是整體二分。
透過重複利用每次檢查時會用到的資訊

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +這時候我們就可以一次去處理多個詢問，透過重複每次檢查時會用到的資訊，來加速程式，也就是整體二分。
也就是整體二分 -> 這個技巧叫做整體二分

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +```
Please provide full code

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +> * \\( 1 \leq  k \leq r - l + 1 \\)
有沒有更裸的題目來介紹整體二分啊？

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +而對於小於等於 \\( mid \\) 的元素，他對 \\( Q_r \\) 內詢問的貢獻都是不變的 ，那不如就在這一層中將這些詢問的 \\( k \\) 扣掉那些元素的數量，這樣一來就不用在 \\( solve(mid + 1, r, Q_r) \\) 中重複計算了，所以變成只需要計算對 \\( Q_r \\) 的貢獻。
why are you using \\?

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +而對於小於等於 \\( mid \\) 的元素，他對 \\( Q_r \\) 內詢問的貢獻都是不變的 ，那不如就在這一層中將這些詢問的 \\( k \\) 扣掉那些元素的數量，這樣一來就不用在 \\( solve(mid + 1, r, Q_r) \\) 中重複計算了，所以變成只需要計算對 \\( Q_r \\) 的貢獻。
這需要更詳細的解釋

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +複雜度的話，會跟不帶修改的版本一樣為 \\( O((n + q)\log n \log C ) \\) 。
看不懂QQ

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +> * \\( n, m, k \leq 3 * 10^5 \\)
\times

2023-07-21 15:58 UTC, harry900831 commented on src/Miscellaneous/ParallelBinarySearch.md
> +* [https://link.springer.com/chapter/10.1007/978-3-319-72547-5_15#Sec20](https://link.springer.com/chapter/10.1007/978-3-319-72547-5_15#Sec20)
Please read more references

2023-07-21 16:02 UTC, harry900831 commented on src/Miscellaneous/CDQ.md
> ++ 動態問題轉為靜態問題 (操作分治)
我認為這一章節：

1. 偏序問題：範例問題沒啥問題
2. 動態問題轉靜態問題：搭配一兩個完整解釋的例題
3. 使用 CDQ 解決斜率優化問題：搭配 CSES 那題 dp 解釋一下

這些當example 就好 剩下的都可以丟 exercise

2023-08-23 16:16 UTC, harry900831 commented
Please resolve the comment if you fix it.

Is this PR ready for review?

2023-08-24 13:46 UTC, chyyen commented
> Please resolve the comment if you fix it.
> 
> Is this PR ready for review?

CDQ 的部分目前已經寫完了差 Markdownlint Error 的部分，但整體二分還需要寫一下，想問學長能不能先將這個 PR 改成只有 CDQ，整體二分我會再開一個 PR 出來

2023-08-25 16:12 UTC, harry900831 commented
Sure~

2023-09-17 19:04 UTC, harry900831 requested changes

2023-09-17 19:04 UTC, harry900831 commented on src/miscellaneous/cdq.md
> +        while (p < 3 * N) {
If you use vector instead of int array, you can avoid the mistake that chasing the size of the array but forget to change the variable over here.

2023-09-17 19:04 UTC, harry900831 commented on src/miscellaneous/cdq.md
> +        i.c = lower_bound(v.begin(), v.end(), i.c) - v.begin() + 1;
use function to avoid duplicate code. It can prevent dumb typo

2023-09-17 19:04 UTC, harry900831 commented on src/miscellaneous/cdq.md
> +};
This class looks pretty scary..

2023-09-17 19:04 UTC, harry900831 commented on src/miscellaneous/cdq.md
> +
The reason why I pull out history from bit structure is to keep bit clean as an template

2023-09-17 19:10 UTC, harry900831 commented
The overall structure LGTM!
The last thing to fix is the code

2023-09-19 03:28 UTC, closed without merging

2023-09-19 08:36 UTC, harry900831 commented
@chyyen why are you closing this?

2023-09-19 10:48 UTC, chyyen commented
Sorry, I accidentally closed the PR, and I didn't know I can reopen the PR at that time, so I just created a new PR.