Add generating_function.md
NTHU-CP/NTHU-CPP pull request #64
Opened 2023-05-14 04:06 UTC by fffelix-huang

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [ ] Rebase to the latest main branch.
- [x] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-05-18 18:57 UTC, harry900831 requested changes
大致瀏覽過了內容：
1. 整體來看說明需要更詳細，現在像是一份筆記而非文章。
2. 要如何應用 GF 去解題，這部分是最重要的但是內容不太夠。例如你每一個subsection 都可以搭配有OJ的例題會比較好。

我先將這個 PR 設定成 draft PR，等你完成之後在轉成 ready for review。到時我會再仔細review。

2023-05-18 18:57 UTC, harry900831 commented on src/math/generating_function.md
> +在計算時，我們會希望能夠把複雜的多項式化簡，變成容易觀察係數的多項式。常見的生成函數有：
把複查的多項式化簡 -> 不一定是多項式吧

2023-05-18 18:57 UTC, harry900831 commented on src/math/generating_function.md
> +五則運算：\\( f(x) \pm g(x), f(x)g(x), \frac{f(x)}{g(x)}, f(x) \% g(x) \\)
% 沒 render 成功

2023-05-18 18:57 UTC, harry900831 commented on src/math/generating_function.md
> +
請使用 bullet list

2023-05-18 18:57 UTC, harry900831 commented on src/math/generating_function.md
> +如同一般的多項式，我們可以對 FPS 進行運算。這些運算與一般的多項式相同。細節和原理請參考其他篇文章，像是多項式乘法可以參考 FFT/NTT。
It would be great if you provide the external resources such as:
https://codeforces.com/blog/entry/56422

2023-05-18 18:57 UTC, harry900831 commented on src/math/generating_function.md
> +> \\( 1 \leq c_i \leq 10^5 \\)
Ditto

2023-05-18 18:57 UTC, harry900831 commented on src/math/generating_function.md
> +> \\( b_i = (\sum_{j = 0}^i \binom{i - j + 1}{k} \cdot a_j) \bmod 998244353 \\)，給定 \\( a_0, \dots, a_{n - 1} \\)，求 \\( b_0, \dots, b_{n - 1} \\)
排版跑掉

2023-06-17 08:20 UTC, harry900831 requested changes
- Overall, the content is great. But we can't expect the reader to have a strong math background, so you might have to provide more explanation on the derivation step.
- Please re-request review after you finish it.
- Please double check all the formula and the derivation step is correct and have no typo by yourself. I might merge this after your next revision.
- Please fix text lint

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +經過一些化簡後得到 \\( f(n, k) \\) 的 OGF 為 \\( F(x, y) = \frac{1}{1 - x - xy} \\)。我們可以觀察 OGF 在單一變數的變化。比如固定 \\( n \\)，也就是求 \\( f_n(k) = \binom{n}{k} \\) 的 OGF，就會是
一些化簡 可以列出怎麼畫減的嗎

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +&= [x^n] \sum_{n = 0}^{\infty} (1 + y)^n x^n \\\\
這一步需要解釋

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +&= [y^k] \frac{1}{1 - x} \sum_{k = 0}^{\infty} (\frac{x}{1 - x})^k y^k \\\\
有幾步需要解釋一下吧

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +# Generating Function
可參考這種寫法：https://github.com/NTHU-CP/NTHU-CPP/blob/6850bb0d76f9d5c8c07c87c6b66f5bf34c754a9b/src/math/sqrt_decomposition.md?plain=1#L117-L122

對於一些推導，個人建議講一下how會讓讀者讀起來比較順

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +&= [x^{n - k}] \frac{1}{(1 - x)^{k + 1}}
why?

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +我們可以從 \\( f_k(n) \\) 的 OGF 得到一些性質，因為
什麼性質

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +因此，\\( \binom{n + k - 1}{k - 1} = [x^n] \frac{1}{(1 - x)^k} \\)。
so?

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +
新增 #exercises
針對每一題給 hint

提供你一些題目：
https://atcoder.jp/contests/abc260/editorial/4469
https://atcoder.jp/contests/abc230/editorial/3027
https://atcoder.jp/contests/abc222/editorial/2765
https://atcoder.jp/contests/abc300/editorial/6286
https://atcoder.jp/contests/abc303/tasks/abc303_h

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +## References
有沒有哪些資源是推薦讀者想要深入研究可以看得，在這邊提一下

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +
個人覺得內容有點少，可以在詳細講解幾題上述的題目

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +## 介紹
在文章最一開始的地方提一下 generating function 在競程比賽的用處以及他可能會需要搭配學會的技巧，例如：當題目的counting 問題轉乘GF後可能可以用 NTT 來運算，或者說 可以拿他來求recursion一般項 

讓讀者在看之前能預期大概會學到啥以及學這內容對他到底有沒有幫助

2023-06-17 08:20 UTC, harry900831 commented on src/math/generating_function.md
> +我們可以用生成函數解遞迴關係式的一般項。舉例來說，如果我們有一個數列
這方式應該只能求線性遞迴關係式？

2023-06-23 14:42 UTC, fffelix-huang commented
@harry900831 我把它切成 4 個 section

2023-06-23 16:02 UTC, harry900831 commented
It looks great at first glance!
I will do detail review in a few days.

2023-06-27 09:12 UTC, harry900831 commented on src/math/gf_recurrence.md
> +因為每次操作都要把一個 \\( h_i = 1 \\) 的往上移動，且經過 \\( n - 1 \\) 次操作後根節點要為 \\( n \\)，因此根節點的初始 \\( h_i = 1 \\)。又因為每次往上移動時最多可以跳過一個節點 (\\ (u, v) \\) 可以為父子或爺孫關係) ，因此樹上不能有相鄰的 \\( 0 \\)，否則無法在 \\( N - 1 \\) 次內完成。
可以跳過一個節點 (\ (u, v) \) 可以為父子或爺孫關係) 

render error

2023-06-27 09:13 UTC, harry900831 commented on src/math/gf_recurrence.md
> +[^note-1]: 假設 \\( A(x)B(x) = 1 \\)，我們稱 \\( B(x) \\) 為 \\( A(x) \\) 的乘法逆元，記做 \\( B(x) = \frac{1}{A(x)} = A(x)^{-1} = A^{-1}(x) \\)。
這是哪裡的 note

2023-06-27 09:14 UTC, harry900831 commented on src/math/gf_combination.md
> +&= \frac{1}{1 - x} \frac{1}{1 - x^5} \frac{1}{1 - x^{10}} \frac{1}{1 - x^{50}} & \text{每個括號內的都是等比級數} \\\\
這一行會有點長 可以考慮把後者的解釋 放在下面

2023-06-27 09:41 UTC, fffelix-huang commented on src/math/gf_recurrence.md
> +[^note-1]: 假設 \\( A(x)B(x) = 1 \\)，我們稱 \\( B(x) \\) 為 \\( A(x) \\) 的乘法逆元，記做 \\( B(x) = \frac{1}{A(x)} = A(x)^{-1} = A^{-1}(x) \\)。
![image](https://github.com/NTHU-CP/NTHU-CPP/assets/72808219/8410fac3-3909-48b9-9f08-5f9861086fa0)
這邊的 但是好像不太明顯

2023-06-27 10:16 UTC, harry900831 commented on src/math/gf_recurrence.md
> +[^note-1]: 假設 \\( A(x)B(x) = 1 \\)，我們稱 \\( B(x) \\) 為 \\( A(x) \\) 的乘法逆元，記做 \\( B(x) = \frac{1}{A(x)} = A(x)^{-1} = A^{-1}(x) \\)。
I see.

2023-06-27 10:54 UTC, fffelix-huang commented
@harry900831 Done. Ready for review.

2023-06-27 12:21 UTC, harry900831 commented
Please fix textlint

2023-06-27 13:32 UTC, fffelix-huang commented
@harry900831 Fixed.

2023-06-27 18:17 UTC, harry900831 approved these changes

2023-06-27 18:17 UTC, merged