Add game_theory.md
NTHU-CP/NTHU-CPP pull request #65
Opened 2023-05-14 05:21 UTC by CY-chang

[#55](https://github.com/NTHU-CP/NTHU-CPP/issues/55)

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [x] Rebase to the latest main branch.
- [ ] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [x] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-05-18 18:19 UTC, harry900831 requested changes
我大致瀏覽過了，我先將其轉乘 draft PR，等你修改好並附上所有練習題後，再將PR 設定成 ready for review.
1. 英文字左右需要空白，除非是標點符號之類得特殊字元。
2. 目前內容有點少，我相信應該有更多定理或是技巧能講。
3. 這個主題的重點會是範例題目，請盡量涵蓋各種與賽局相關的題目與應用。

2023-05-18 18:19 UTC, harry900831 commented on src/math/game_theory.md
> +### Example
I believe providing an easier example to introduce game theory is better.
For example:

兩人 100顆石頭，輪流每人每次可以取 1 ~ 7 顆，沒石頭拿的就輸了，請問誰穩贏。

2023-05-18 18:19 UTC, harry900831 commented on src/math/game_theory.md
> +## Reference
references

2023-06-14 06:26 UTC, CY-chang commented
@harry900831 
Hi, I've added some exercises and their editorials. For the introduction part, I couldn't find an Online Judge with the problem you mentioned. So I replaced it with a similar one on CSES. Should I add more exercise problems, or should I focus on expanding the content related to the Nim and Grundy numbers section (not quite sure what to add) ?
Thanks for your feedback!

2023-06-18 22:44 UTC, harry900831 requested changes
I think you can rename this Topic to "Nim and Sprague-Grundy Theorem". If you don't know what to add for the theorem part, I think you can add more example problem. 

There's a lot of cool and interesting problem that is related to game theory and it doesn't require any special theorem.

For example: 

一個 n*m 的巧克力在桌上，兩人輪流拿一片起來橫斷或直斷，直到沒有 1*1 以外的塊，沒得操作的人輸

or

ZeroJudge] b902. 肉墊遊戲


(Although, I believe there should be some theorem behind those problem)

2023-06-18 22:44 UTC, harry900831 commented on src/math/game_theory.md
> +### Example
我認為這題不需要真的有OJ 連結，這只是讓讀者迅速理解這章節大概是什麼樣子的內容與讓他們腦力激盪而已。

2023-06-18 22:47 UTC, harry900831 commented
If you have no idea, read more online resources may be helpful.

2023-06-23 16:15 UTC, harry900831 commented
The content looks great at first glance, I will do detail review in a few days.

2023-06-30 10:35 UTC, harry900831 requested changes
- use \times instead of *
- In my opinion, there's a lot of part that can be shorter. Please try to use less word but with clear meaning to explain stuff.
- You should have detail explanation on the theorem part.
- It's very great that you have a lot of problem as an example
- there're a lot of parts that didn't render successfully, please check it.

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +有 \\( N \\) 堆石頭，每堆有 \\( a_i \\) 個。玩家 A，B 輪流取石頭，每次可以選擇一堆，並從該堆取出任意數量的石頭(不能不取)。沒有石頭可以取的玩家落敗。
A、B

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +得到的答案若為 \\( 0 \\)，代表當前的局勢為 losing state，答案不為 \\( 0 \\) 則為 winning state。
將每堆的石頭個數進行 xor 若得到的數值為 0 代表是 losing state 先手必輸，或不為 0 則為 winning state，先手必贏。

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +綜上所述以及數學歸納法，且遊戲在有限的回合數內會結束，因此該策略是正確的。
看不出這數學歸納法是在歸納什麼

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +- \\( 1 \leq N \leq 2*10^5 \\)
\times

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +> 有 \\( N \\) 階的階梯，編號為第 \\( 1 \sim N \\) 階，每階上都放有非負整數顆球。玩家 \\( A\, B \\) 輪流採取行動，由 \\( A \\) 開始。每回合可以選擇一個整數 \\( x \\) \\( (x > 1) \\)，並從第 \\( x \\) 階取任意正整數顆球並移到第 \\( x - 1 \\) 階。到最後，沒有任何方法移動球的一方落敗。題目則
missing problem size

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +該如何驗證這個策略的正確性呢?這邊提供一個與 Nim Game 有關的想法。將偶數階階梯的球數視為 Nim Game 每堆的石頭數，且每回合的行動是可以任取一堆並增加該堆石頭數的。而對於一個偶數 \\( K\ (K \geq 2) \\)，若當時第 \\( K + 1 \\) 階有 \\( x \\) 顆球，則代表第 \\( K \\) 階的石頭堆在當時的回合最多可以新增 \\( x \\) 塊
解釋不夠清楚

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +在介紹此定理以前，先引入一個符號 \\( MEX \\)。對於一個集合 \\( s \\)，\\( MEX \lbrace s \rbrace \\) 的定義為不屬於 \\(s \\) 的數字中最小的非負整數。例如 \\( MEX \lbrace 0, 1, 3, 5 \rbrace = 2 \\)，\\( MEX \lbrace 1, 2, 3 \rbrace = 0 \\)。根據 Sprag
需要清楚的 state 出這個 theorem 是什麼

可能可以用 ::: :::

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +在介紹此定理以前，先引入一個符號 \\( MEX \\)。對於一個集合 \\( s \\)，\\( MEX \lbrace s \rbrace \\) 的定義為不屬於 \\(s \\) 的數字中最小的非負整數。例如 \\( MEX \lbrace 0, 1, 3, 5 \rbrace = 2 \\)，\\( MEX \lbrace 1, 2, 3 \rbrace = 0 \\)。根據 Sprag
那 非 0 的grundy number 怎麼定義？

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +定理的證明可以利用數學歸納法與 \\( XOR \\) 的性質。但這裡提供一個直觀的想法供讀者參考:
Get 不到這個直觀的想法

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +另外，若遊戲方式為好幾個子遊戲同時進行。我們可以採用與 Nim Game 相似的作法，將若干個子遊戲的 Grundy Number 使用 \\( XOR \\) 來進行合併，得出整個遊戲的狀態。
這句話放在這裡我相信讀者也會看不懂

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +在介紹此定理以前，先引入一個符號 \\( MEX \\)。對於一個集合 \\( s \\)，\\( MEX \lbrace s \rbrace \\) 的定義為不屬於 \\(s \\) 的數字中最小的非負整數。例如 \\( MEX \lbrace 0, 1, 3, 5 \rbrace = 2 \\)，\\( MEX \lbrace 1, 2, 3 \rbrace = 0 \\)。根據 Sprag
喔喔 我看到下面的例題就看懂了

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +另外，若遊戲方式為好幾個子遊戲同時進行。我們可以採用與 Nim Game 相似的作法，將若干個子遊戲的 Grundy Number 使用 \\( XOR \\) 來進行合併，得出整個遊戲的狀態。
這感覺是需要證明的東西？

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +> 一開始有 \\( x \\) 根棍子放在同一堆。玩家 A, B 輪流採取行動。每次行動可以選擇其中一堆並將其分成兩堆，而且這兩堆的大小不能相同。沒有合法的行動者落敗。問雙方都採取最佳化策略，那麼誰將獲勝。
有online judge 嗎？

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +以 \\( x = 5 \\) 為例，因為 \\( f(5) > 0 \\)，代表當前的狀態是 winning state。同時也代表著玩家可以採取某個行動，使遊戲狀態的 Grundy Number 變為 \\( 0 \\)，也就是 losing state。在這個局勢，玩家只要把這堆棍子分成 \\( 1 \\) 根與 \\( 4 \\) 根，則 Grundy Number 會變成 \\( f(
summary for this problem?

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +在一次行動後，不含有 \\( 1 \\) 號節點的聯通塊會被移除。因此把根定在 \\( 1 \\) 號節點似乎是個合理的想法。接著要思考的是如何定義狀態。樹具有可以遞迴的特性。如果我們有子樹的狀態，有沒有辦法把那些答案合併，並求出父節點的答案呢? 基於上述的推論，我們可能會聯想到 Grundy Number。若一個子樹的根結點編號為 \\( x \\)，我們定義在這棵子樹上玩相同的遊戲時，Gru
what's the difference between grundy number and sg value?

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +在一次行動後，不含有 \\( 1 \\) 號節點的聯通塊會被移除。因此把根定在 \\( 1 \\) 號節點似乎是個合理的想法。接著要思考的是如何定義狀態。樹具有可以遞迴的特性。如果我們有子樹的狀態，有沒有辦法把那些答案合併，並求出父節點的答案呢? 基於上述的推論，我們可能會聯想到 Grundy Number。若一個子樹的根結點編號為 \\( x \\)，我們定義在這棵子樹上玩相同的遊戲時，Gru
f_x or f(x)? 
Please be consistent throughout whole article

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +<details><summary>Solution</summary>
missing space before and after Solution

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +<details><summary> Solution Code </summary>
solution code should be inside solution

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +第一眼看到題目可能會覺得狀態不太容易定義。但再想想會發現若把遊戲狀態定義成目前可選擇的範圍是 \\( x \sim y \\)。那麼取完一個區間後，會得到另外兩個可以選的小區間，也就是兩個同類型的子遊戲。這與前面 Grundy Number 章節的概念頗為相似。考慮將狀態定義為 \\( dp\[x\]\[y\] \\)，代表當現在可選的範圍是 \\( x \sim y \\) 時，狀態的 Gru
dp[x][[y] -> f(x, y)

2023-06-30 10:35 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +另外，我們必須求出轉移到的狀態的 SG value，也就是被分出來的那幾堆的 SG value 做 \\( XOR \\)運算。但慢慢做需要 \\( O(sqrt(N)) \\)，總複雜度變成 \\( O(N *sqrt(N)* sqrt(N)) = O(N ^ 2) \\)，會超時。因此我們需要一個更快的作法。觀察到被拆出來的石頭堆會形成公差為 \\( 1 \\) 的等差數列。因此我們可以構造
render error

2023-06-30 10:35 UTC, harry900831 commented on src/math/game_theory.md
> +接著分析 A 採取追擊的策略。首先 A 在不會踩到陷阱的前提下每回合都會前進 \\( 4 \\) 步。而 B 在看到 A 大步數前進，根據上方的說明，B 於是知道 A 採取的是追擊策略，因此除了第一步以外，B 的每個回合都會前進 \\( 3 \\) 步。因此要討論的只有 B 以 \\( 2 \\) 步開局或是以 \\( 3 \\) 步開局這兩種情況了。若 B 以 \\( 3 \\) 步開局，代表
例如這裡每一段的文字都很多，閱讀起來會不太順。
可以考慮搭配圖並必精簡你的文字同時不犧牲傳遞的資訊量。

2023-06-30 10:54 UTC, CY-chang commented on src/SUMMARY.md
> +  - [Nim and Sprague-Grundy Theorem](math/nim_and_sg_value.md)
Under misc seems better. I'll move the location of the files.

2023-07-01 06:46 UTC, CY-chang commented on src/math/nim_and_sg_value.md
> +在一次行動後，不含有 \\( 1 \\) 號節點的聯通塊會被移除。因此把根定在 \\( 1 \\) 號節點似乎是個合理的想法。接著要思考的是如何定義狀態。樹具有可以遞迴的特性。如果我們有子樹的狀態，有沒有辦法把那些答案合併，並求出父節點的答案呢? 基於上述的推論，我們可能會聯想到 Grundy Number。若一個子樹的根結點編號為 \\( x \\)，我們定義在這棵子樹上玩相同的遊戲時，Gru
Two terms mean the same thing. Should I choose one and use it throughout the whole article?

2023-07-21 16:15 UTC, harry900831 commented
Are you ready for review?

2023-07-22 04:43 UTC, CY-chang commented
> Are you ready for review?

Yes, most of the problems are fixed.

2023-07-22 05:00 UTC, CY-chang commented on src/math/nim_and_sg_value.md
> +在介紹此定理以前，先引入一個符號 \\( MEX \\)。對於一個集合 \\( s \\)，\\( MEX \lbrace s \rbrace \\) 的定義為不屬於 \\(s \\) 的數字中最小的非負整數。例如 \\( MEX \lbrace 0, 1, 3, 5 \rbrace = 2 \\)，\\( MEX \lbrace 1, 2, 3 \rbrace = 0 \\)。根據 Sprag
不太了解。是要將內文出現的"Sprague-Grundy Theorem"都改格式嗎，還是說把這段以正式的 theorem 來呈現

2023-07-22 09:59 UTC, harry900831 commented on src/math/nim_and_sg_value.md
> +在介紹此定理以前，先引入一個符號 \\( MEX \\)。對於一個集合 \\( s \\)，\\( MEX \lbrace s \rbrace \\) 的定義為不屬於 \\(s \\) 的數字中最小的非負整數。例如 \\( MEX \lbrace 0, 1, 3, 5 \rbrace = 2 \\)，\\( MEX \lbrace 1, 2, 3 \rbrace = 0 \\)。根據 Sprag
這段已正式的 theorem 來呈現

:::
Sprague-Grundy Theorem

(It's definition)
:::

2023-08-25 09:31 UTC, fffelix-huang requested changes
都看過了，再檢查看看有沒有地方沒有 render 到~

2023-08-25 09:31 UTC, fffelix-huang commented on src/misc/game_theory.md
> +在賽局的題目中，必勝方通常可以維持某種不變量。觀察並定義出不變量往往是解賽局題目的關鍵。以 Introduction 拿石頭的題目為例，不變量是在兩人操作結束後，剩餘數量維持在 \\( 8 \\) 的倍數。而後面章節會介紹的 Nim Game，不變量則為兩人操作結束後，所有堆數的 \\( XOR \\) 等於 \\( 0 \\)。
讀者還不知道 Nim Game 是甚麼，堆數是什麼。或許這邊可以先不用提到 Nim Game，到 Nim Game 的 chapter 再分析他的 invariant？

2023-08-25 09:31 UTC, fffelix-huang commented on src/misc/game_theory.md
> +時間複雜度為: \\( O(log(max\lbrace x, y \rbrace)) \\)
\log

2023-08-25 09:31 UTC, fffelix-huang commented on src/misc/nim_and_sg_value.md
> +詳細的證明可以參考[這篇文章](https://zhuanlan.zhihu.com/p/20611132)。但這裡提供一個直觀的想法供讀者參考: 試著把不偏賽局的 Grundy Number 與 Nim Game 做連結。Nim Game 每回合的行動可以從數量為 \\( x(x>0) \\) 的石頭堆取出任意數量，在取後的剩餘石頭數可以是 \\( 0 \sim x-1 \\) 的任意一個。同
SG value 或是 Grundy Number，選一個用

2023-08-25 09:31 UTC, fffelix-huang commented on src/misc/nim_and_sg_value.md
> +詳細的證明可以參考[這篇文章](https://zhuanlan.zhihu.com/p/20611132)。但這裡提供一個直觀的想法供讀者參考: 試著把不偏賽局的 Grundy Number 與 Nim Game 做連結。Nim Game 每回合的行動可以從數量為 \\( x(x>0) \\) 的石頭堆取出任意數量，在取後的剩餘石頭數可以是 \\( 0 \sim x-1 \\) 的任意一個。同
x 沒 render 到

2023-08-25 15:59 UTC, harry900831 commented on src/misc/game_theory.md
> +在賽局的題目中，必勝方通常可以維持某種不變量。觀察並定義出不變量往往是解賽局題目的關鍵。以 Introduction 拿石頭的題目為例，不變量是在兩人操作結束後，剩餘數量維持在 \\( 8 \\) 的倍數。而後面章節會介紹的 Nim Game，不變量則為兩人操作結束後，所有堆數的 \\( XOR \\) 等於 \\( 0 \\)。
我覺得這邊需要至少兩個例子
如果找不到其他比 nim game 更好的例子 就維持就好
反正他有提是後面章節

2023-09-10 09:35 UTC, harry900831 commented
@CY-chang Hi, your PR is almost ready to be merged, have you fixed all the comments?

2023-09-14 11:08 UTC, CY-chang commented
> @CY-chang Hi, your PR is almost ready to be merged, have you fixed all the comments?

Yes, I believe all of them are fixed.

2023-09-14 17:44 UTC, merged