Add LCA
NTHU-CP/NTHU-CPP pull request #67
Opened 2023-05-14 08:33 UTC by didwhddks

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [ ] Rebase to the latest main branch.
- [ ] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [x] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-05-18 19:14 UTC, harry900831 requested changes
大致瀏覽了一下，幾點建議
- 新增對高度分塊的LCA 作法，這裡面有介紹。https://www.topcoder.com/thrive/articles/Range%20Minimum%20Query%20and%20Lowest%20Common%20Ancestor
- 需要簡介 LCA 的性質，以及最後提供一些例題能使用 LCA去解。
- 在說明可以將 LCA 轉換成 RMQ 問題後，不需要針對怎麼做 RMQ 問題有過多著墨，未來可能會有 RMQ 問題的文章，可以直接 refer 到那邊

我先將此 PR 轉成 draft PR，等你完成時再轉成 ready for review，到時我會再更詳細的去review，謝謝。

2023-06-07 08:29 UTC, didwhddks commented
@harry900831 助教你好，我已經大致完成了文章的初步架構，目前還缺 LCA 的例題以及高度分塊 LCA 的 sample code。想先請助教幫我 review 一下目前的文章內容。

2023-06-15 12:37 UTC, harry900831 requested changes
Overall, you did a great job!
Please fix textlint, thanks.

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +以上所有 DSU 的操作都可以用 union-by-rank 和 path compression 來優化。因此針對離線的查詢，Tarjan's algorithm 可以有效率地在 \\( O((N+Q)\alpha(N)) \\) 的時間內完成，相當趨近於線性時間。
DSU -> Disjoint Set

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +以上所有 DSU 的操作都可以用 union-by-rank 和 path compression 來優化。因此針對離線的查詢，Tarjan's algorithm 可以有效率地在 \\( O((N+Q)\alpha(N)) \\) 的時間內完成，相當趨近於線性時間。
你這句話應該在時間複雜度分析之前提

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +此小節主要關注於如何利用樹重鏈剖分的概念來查詢點對的最近共同祖先，如果讀者對於樹重鏈的定義以及其相關操作（跳輕邊）還不太清楚的話，建議可以先去觀看相關章節。
Here should be a link to https://github.com/NTHU-CP/NTHU-CPP/pull/62.
Maybe we could add this link after HLD be merged.

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +#### 建立尤拉路徑
Eulerian path
尤拉 或 歐拉
可能可以跟讀者說一下兩種翻譯都有人用

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +觀察尤拉路徑我們可以發現，假設我們想知道點對 \\( (u,\ v) \\) 的最近共同祖先是誰，我們只要沿著尤拉路徑從點 \\( u \\) 到點 \\( v \\) 找路徑上深度最淺的點就會是點對 \\( (u,\ v) \\) 的 LCA，因為從點 \\( u \\) 到點 \\( v \\) 必定會先返回其 LCA，然後再到點 \\( v \\)，在這之間也不會出現比其 LCA 深度更淺
u, v 可能會出現很多次->取第一次出現即可

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +觀察尤拉路徑我們可以發現，假設我們想知道點對 \\( (u,\ v) \\) 的最近共同祖先是誰，我們只要沿著尤拉路徑從點 \\( u \\) 到點 \\( v \\) 找路徑上深度最淺的點就會是點對 \\( (u,\ v) \\) 的 LCA，因為從點 \\( u \\) 到點 \\( v \\) 必定會先返回其 LCA，然後再到點 \\( v \\)，在這之間也不會出現比其 LCA 深度更淺
正確性需要說明

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +觀察尤拉路徑我們可以發現，假設我們想知道點對 \\( (u,\ v) \\) 的最近共同祖先是誰，我們只要沿著尤拉路徑從點 \\( u \\) 到點 \\( v \\) 找路徑上深度最淺的點就會是點對 \\( (u,\ v) \\) 的 LCA，因為從點 \\( u \\) 到點 \\( v \\) 必定會先返回其 LCA，然後再到點 \\( v \\)，在這之間也不會出現比其 LCA 深度更淺
包含為什麼取第一次就好

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +<img src="image/LCA/RMQ_4.png" width="700" style="display:block; margin: 0 auto;"/>
範例中K=2

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +為了比較好的時間複雜度，一般我們會取 \\( K \\) 等於 \\( 0.5\log N \\)，這樣我們就可以把預處理的時間複雜度壓到 \\( O(N) \\)。
why 0.5 log N?
can't K = logN get the same O(N) - O(1) either?

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +  - 對 Block 陣列建 Sparse Table：\\(O\left(\frac{N}{K}\log\frac{N}{K}\right) \xrightarrow{K=0.5\log N} O(N) \\)
稍微推導一下吧

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +#### 高度分塊區間最小值查詢
I think O(n) -- O(1) LCQ is a better title

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +</details>
最後補一句：這個方法常數很高 比賽中不實用 但是個很漂亮的做法達到理論最佳 online O(n) O(1)

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +
https://codeforces.com/contest/609/problem/E

In my opinion, you can add this problem as an exercise, to teach the reader that you can use binary lifting to maintain the maximum weight edge on a tree path.

2023-06-15 12:37 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +
(It would be great if you could provide code)

2023-06-15 12:47 UTC, harry900831 requested changes

2023-06-15 12:47 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +透過此轉換，我們可以發現新塊最多只會有 \\( 2^{K-1} \\) 種。而轉換後有著相同內容的塊，塊內所有區間組合的最小值在塊內所對應的 index offset 都會是相同的，因為新塊內容其實間接說明了原塊內的深度分布。因此，相較於每次查詢時都去暴力搜索塊內的最小值，我們其實可以預處理每一種新塊內所有區間組合的最小值在塊內所對應的 index offset，這部分會花費 \\( O(2^{
舉個例吧

2023-06-18 11:42 UTC, harry900831 requested changes
Please resolve the comment by yourself if you fix it. If you want to discuss about it, just directly reply to it.

2023-06-18 11:42 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +一個直觀的做法是先從根開始作一次 DFS，確認出每個點的父節點以及時間戳（第一次訪問與最後一次訪問的時間）。接著針對詢問，我們可以藉由預處理好的的資訊暴力往上搜索所求點對 \\( (u,\ v) \\) 中深度較淺的點的祖先，直到當前搜索的點同時也為另一點的祖先，該點即為點對 \\( (u,\ v) \\) 的最近共同祖先。而確認一個點是否為另一點的祖先，我們可以利用時間戳在 \\( O(1)
> 第一次訪問與最後一次訪問的時間

DFS 進行遞迴時進入該節點與離開該節點時間戳記

2023-06-18 11:42 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +一個直觀的做法是先從根開始作一次 DFS，確認出每個點的父節點以及時間戳（第一次訪問與最後一次訪問的時間）。接著針對詢問，我們可以藉由預處理好的的資訊暴力往上搜索所求點對 \\( (u,\ v) \\) 中深度較淺的點的祖先，直到當前搜索的點同時也為另一點的祖先，該點即為點對 \\( (u,\ v) \\) 的最近共同祖先。而確認一個點是否為另一點的祖先，我們可以利用時間戳在 \\( O(1)
解釋一下怎麼用時間戳記O(1) 判斷祖先

2023-06-18 11:42 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +除了抬升的優化以外，對於等深度的兩點找 LCA 本身具有單調性，直覺上可以利用二分搜來加速。但在稍早提到的 Brute force 當中，我們並沒有提到相關的操作。原因是因為我們只記錄了每個點的父節點的資訊，在處理二分搜的檢查函數上會花費線性的時間，導致整個二分搜的時間複雜度為 \\( O(N\log N) \\)，明顯沒有比較快。
還是沒有解釋怎麼二分艘

2023-06-18 11:42 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +#### 高度分塊區間最小值查詢
There is a typo, I mean O(n) - O(1) LCA...

2023-06-18 11:42 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +為了比較好的時間複雜度，一般我們會取 \\( K \\) 等於 \\( 0.5\log N \\)，這樣我們就可以把預處理的時間複雜度壓到 \\( O(N) \\)。
So why 0.5 log N not K = logN?

2023-06-18 11:42 UTC, harry900831 commented on src/tree/lowest_common_ancestor.md
> +關於為什麼這樣做會給我們 minimal 的結果，有興趣的讀者可以參考本文附上的參考資料。
which one

2023-06-18 16:09 UTC, harry900831 commented
I've uploaded the score in advance. I'll merge it after it's finalized.

2023-06-18 16:41 UTC, didwhddks commented
@harry900831 助教你好，因為我下個星期都會在國外，所以在 23 號前可能沒辦法 finish 所有的 requested changes。關於 grading 的部分，助教可以先進行，我回國之後會繼續完成剩餘的 requested changes。

2023-06-18 16:44 UTC, harry900831 commented
Got it, I've uploaded the score. Please check it on eeclass.

2023-06-27 04:07 UTC, closed without merging