Add Fast Fourier Transform
NTHU-CP/NTHU-CPP pull request #68
Opened 2023-05-14 09:05 UTC by TimmyChiang

Note: 
- Finish concepts
- Haven't finish Exercises and Solutions

- [ ] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [ ] Rebase to the latest main branch.
- [ ] List all the references.
- [ ] Successfully build the website by mdBook with no error after the change.
- [ ] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [ ] Review the content by myself.
- [ ] Pass tests/CI.

2023-05-18 18:27 UTC, harry900831 commented
I've turned this PR to draft PR since there's a draft on the title.
Please set it to ready for review after you finish it.
Thanks.

2023-06-23 08:28 UTC, TimmyChiang commented
嗨~ 很抱歉沒有辦法把 issue 中的題目全部完成。目前只有將模板題和兩題基本的 string matching 題目放上去。

2023-06-23 16:35 UTC, harry900831 commented
Please fix your commit history...

2023-06-24 04:21 UTC, TimmyChiang commented
Commit history fixed.

2023-07-10 13:54 UTC, harry900831 requested changes
Overall, there's still lack of explanation. Please try to figure out how to make your article clear and easy for a CS major student at maybe 3rd grade.

2023-07-10 13:54 UTC, harry900831 commented on src/SUMMARY.md
> +  - [Fast Fourier Transform](miscellaneous/fast_fourier_transform.md)
This should be under math

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +給定方程式 \\( z^n = 1 \\), 其中 \\( n \\) 為正整數，\\( z \\) 為複數。我們稱 \\( z \\) 為該方程式的 \\( n \\) 次單位根。設 \\( \omega_n = e^{\frac{2 \pi i}{n}} \\), 該方程式的 \\( n \\) 次單位跟有 \\( n \\) 個，分別為 \\( \omega_n, \omega_n^2,
設 \\( \omega_n = e^{\frac{2 \pi i}{n}} \\), 該方程式的 \\( n \\) 次單位跟有 \\( n \\) 個，分別為 \\( \omega_n, \omega_n^2, \cdots, \omega_n^{n-1} \\) 和 \\( 1 \\).


這句看不懂需要多點解釋

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +根據點值表示式的唯一性，我們知道 DFT 是個一對一映成函數。故可以將 \\( a \\) 表示為，\\( a = \text{DFT}_n^{-1}(y) \\).
Need more explanation

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +觀察發現 \\( A^{[0]}(x) \\) 和 \\( A^{[1]}(x) \\) 的次方均為 \\( A(x) \\) 的一半。換言之，計算 \\( A(x) \\) 只需計算兩個次方為 \\( A(x) \\) 一半的值再相加即可。\\( y \\) 中的元素共有 \\( n \\) 個，表示我們要將 \\( n \\) 個 \\( x \\) 代入 \\( A(x) \\) 計算結果
次方均為 \\( A(x) \\) 的一半 -> 項數均為一半

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +得總時間為 \\( O(n \log n) \\). 值得一提的是，這裡所有的變數 \\( x \\) 可以是任意複數。
看不懂這是要計算什麼...

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +得總時間為 \\( O(n \log n) \\). 值得一提的是，這裡所有的變數 \\( x \\) 可以是任意複數。
以及那遞迴是怎麼來的

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +$$
你前面那麼早就介紹這個矩陣
讀者到這邊反而會ㄇㄤ 掉？

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +### 模板
Maybe you have to describe the use of double and long long, would it cost floating point error and so on.

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +本題與前一題 [SPOJ - Maximum Self-Matching](https://www.spoj.com/problems/MAXMATCH/) 類似。差異處只有兩點，第一是 ```a```, ```b```, 和 ```c``` 變成 ```A```, ```T```, ```C```, 和 ```G```. 第二是 hamming distance 即自己字串的長度扣掉匹配數。
If possible, please use CSES, CF, Atcoder as the source of the problem.

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +本題與前一題 [SPOJ - Maximum Self-Matching](https://www.spoj.com/problems/MAXMATCH/) 類似。差異處只有兩點，第一是 ```a```, ```b```, 和 ```c``` 變成 ```A```, ```T```, ```C```, 和 ```G```. 第二是 hamming distance 即自己字串的長度扣掉匹配數。
There should be two section:

1. Example problem, you have to explain the problem in detail.
2. Excercise problem, the problem list for reader to exercise.

For example: https://nthu-cp.github.io/NTHU-CPP/sqrt/sqrt_decomposition.html

2023-07-10 13:54 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +本題與前一題 [SPOJ - Maximum Self-Matching](https://www.spoj.com/problems/MAXMATCH/) 類似。差異處只有兩點，第一是 ```a```, ```b```, 和 ```c``` 變成 ```A```, ```T```, ```C```, 和 ```G```. 第二是 hamming distance 即自己字串的長度扣掉匹配數。
Also for some problem, it would be great to see the AC code that use the template code you provide.

2023-07-10 13:55 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +本題與前一題 [SPOJ - Maximum Self-Matching](https://www.spoj.com/problems/MAXMATCH/) 類似。差異處只有兩點，第一是 ```a```, ```b```, 和 ```c``` 變成 ```A```, ```T```, ```C```, 和 ```G```. 第二是 hamming distance 即自己字串的長度扣掉匹配數。
Also, I believe there's a lot of cool application for FFT, please include more interesting problem.

2023-07-15 07:11 UTC, TimmyChiang commented on src/miscellaneous/fast_fourier_transform.md
> +$$
當初想說把背景知識（工具）一口氣講完後再講怎麼去使用。目前想到兩個解決方法，第一個是直接把范德蒙矩陣從背景知識拿掉，到這邊再拉出來介紹。另一個是背景知識的部分不動，這邊再做回顧就好。你覺得哪個可能比較適合，或是有沒有其他解決方法~

2023-07-15 07:15 UTC, harry900831 commented on src/miscellaneous/fast_fourier_transform.md
> +$$
我沒什麼想法
你可以多參考其他你覺得寫得不錯的人的做法

2023-08-24 15:52 UTC, TimmyChiang commented
> friendly ping

Got it. Thanks!

2023-09-04 15:04 UTC, closed without merging