Add aliens optimization draft
NTHU-CP/NTHU-CPP pull request #70
Opened 2023-05-14 12:28 UTC by llshang

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [x] Rebase to the latest main branch.
- [x] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-06-22 11:35 UTC, llshang commented
@harry900831 

I have completed my task, please review. 
Sorry for the delay in requesting the review.

2023-07-10 14:37 UTC, harry900831 requested changes
Please re-request review after your revision. Thanks.

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +事實上，這樣的技巧最早是在 2012 年，由王欽石在中國國家集訓隊的「淺析一類二分方法」中提出，因此，此方法又稱為「WQS 二分」。而自 IOI 2016 的 [Aliens](https://ioinformatics.org/files/ioi2016problem6.pdf) 這道題開始，讓這樣的技巧開始受到關注，也因此在近幾年得名並流行起來。
淺析一類二分方法 請附上中國集訓隊論文連結

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +能夠應用到這個技巧的題目中，我們首先將題目看作為在一函數 \\(f\\) 上，求對於某一 \\(f(x)\\) 的值為何。然而，雖然能夠在有效率的時間找到函數 \\(f\\) 的極值，但卻無法在有效率的時間內直接找到 \\(f(x)\\) 為何。
看不懂這句話

能找到極值卻有不能知道f(x) 為何？

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +不過，若是函數 \\(f\\) 是一凹函數（Concave function），又或是說在該函數上的每一點之切線斜率非嚴格遞減或遞增，我們便可以應用 Aliens 優化的技巧來解決此問題。
又或是說在該函數上的每一點之切線斜率先非嚴格遞減後非嚴格遞增

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +然而，若是函數 \\(f\\) 是一凹函數的情況成立，我們便可以以二分搜的方式，找尋適合的 \\(c\\) 值來調整新函數。
這部分一樣看不太懂

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +上述的敘述可能較為複雜，因此在接下來的內容中，我們將透過一道例題，來去深入了解上述步驟的過程。
如果你想不到怎麼好好的修 introduction 讓他夠直觀體會到 aliens 在幹嘛可以考慮直接帶題目

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +## 使用 Aliens 優化
這標題應該下在要開始優化的時候

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +令 \\(dp(i,\ j)\\) 代表自第 \\(0\\) 盞燈至欲點亮第 \\(i\\) 盞燈止，已點亮 \\(j\\) 盞燈的最大總獎賞值，再進一步令 \\(dp_0(i,\ j)\\) 代表沒點亮第 \\(i\\) 盞燈，\\(dp_1(i,\ j)\\) 代表有點亮；\\(A_i\\) 代表上述所提到的獎賞值。
使用 f(i, j) instead of dp(i, j)

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +答案將會是 \\(max(dp_0(N-1,\ R),\ dp_1(N-1, R))\\)。而這樣的 DP 作法使時間複雜度來到 \\(O(NR)\\)，不理想的時間複雜度將使得無法通過此題。
題目是 1-based 你這邊又是 0-based?

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +<img src="image/aliens/aliens-1.png" width="500" style="display:block; margin: 0 auto;"/>
根據你的敘述，我完全不覺得這很trivial

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +我們可以發現 \\(f\\) 函數定義在整數上是一個凹函數，同時是一個上凸包，也就是一個滿足 \\(f(x+1)-f(x) \le f(x)-f(x-1)\\) 的函數，它的差分呈現了非嚴格遞減的關係。
需不需要要先定義一下 凹函數 上凸包 我看到這邊是覺得怪怪的才發現這其實有歧異https://zh.wikipedia.org/zh-tw/凹函数

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +現在，我們暫時去除題目中對於恰好點亮 \\(R\\) 盞燈的限制，假設 \\(f(x)\\) 是點亮 \\(x\\) 盞燈所能獲得的最佳收益，原題的所求便是 \\(f(R)\\) 的值。
f(x) 的定義在更完整一點

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +我們可以發現 \\(f\\) 函數定義在整數上是一個凹函數，同時是一個上凸包，也就是一個滿足 \\(f(x+1)-f(x) \le f(x)-f(x-1)\\) 的函數，它的差分呈現了非嚴格遞減的關係。
\\(f(x+1)-f(x) \le f(x)-f(x-1)\\) 的函數，它的差分呈現了非嚴格遞減的關係。

這真的是對的嗎？

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +以更白話的方式來說明，這樣的凹函數說明了一件事情：點亮的燈太少將會使得得以獲得的獎賞值降低；太多將會使得多個兩兩點亮的燈相鄰，兩者都會使得能夠獲得的最大總獎賞值有所降低。
我們現在的問題已經限制 R <= N/2 了
所以最佳獎賞值發生時不應該會有兩兩相林？

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +<img src="image/aliens/aliens-1.png" width="500" style="display:block; margin: 0 auto;"/>
Aliens 優化難的一點是需要觀察出有這種性質
你需要給讀者一個清楚直覺的解釋

或者說要提供詳細證明

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +\\(dp_1(i) = (A_{i-1}+A_i)+dp_0(i-1)\\)
Ditto

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +\\(dp_1(i) = (A_{i-1}+A_i)+dp_0(i-1)\\)
你的dp式看起來也不讓兩兩相林這與你前者的解釋就毛頓了

因此我認為直覺上反而是 R 越多 代表 x 越大 價值越高才對？

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +<img src="image/aliens/aliens-2.png" width="500" style="display:block; margin: 0 auto;"/>
這圖看不懂

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +<img src="image/aliens/aliens-1.png" width="500" style="display:block; margin: 0 auto;"/>
圖的 y 應該放 f(x) 畢竟你沒講什麼是 y

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +<img src="image/aliens/aliens-3.png" width="500" style="display:block; margin: 0 auto;"/>
看不懂QQ

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +
what is R and c, c 又為什麼小寫

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +以上述的題目為例，這樣的方法也能讓我們將原本得用 \\(O(NR)\\) 的時間複雜度解決的問題，能夠藉此少了一個維度 \\(R\\)，讓時間複雜度變成 \\(O(N\log c)\\)。
請在更簡單清楚地做 aliens 優化的總結

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +```
事實上 aliens dp 多數隊伍也都會帶個模板 例如：https://github.com/OmeletWithoutEgg/ckiseki/blob/master/codes/Misc/Aliens.cpp

你這邊也附上一份，然後這篇文章提到的題目都使用你的模板來做

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +事實上，在本文的參考文獻（IOICamp Handout）中，有提到將題目轉換成上述函數後，其凹凸性的證明並不容易（本文例題作者提供的[題解](https://atcoder.jp/contests/abc218/editorial/2634)中，有提供該函數為凹函數的證明）。因此，很多時候必須得靠一些直覺來確認題目是否存在該性質，或在賽中不知道如何證明的情況下，得需要嘗試利用較小的 case
我原本期待這篇文章會寫凹凸性的證明

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +事實上，在本文的參考文獻（IOICamp Handout）中，有提到將題目轉換成上述函數後，其凹凸性的證明並不容易（本文例題作者提供的[題解](https://atcoder.jp/contests/abc218/editorial/2634)中，有提供該函數為凹函數的證明）。因此，很多時候必須得靠一些直覺來確認題目是否存在該性質，或在賽中不知道如何證明的情況下，得需要嘗試利用較小的 case
事實上我認為一直不放證明只會讓讀者永遠只靠猜有這個性質

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +> \\(N \le 2 \times 10^6, k \le N\\)
可以放後者並講解後者就好

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +
為什麼不介紹 aliens 那一題

2023-07-10 14:37 UTC, harry900831 commented on src/DP/aliens.md
> +> - \\(R \le N-1\\)
這一題真的是最好的 example 嗎？

事實上他對題目做了一層轉換才能得出性質

沒有更裸的題目嗎？

2023-07-10 14:38 UTC, harry900831 requested changes
Please re-request review after your revision. Thanks.

2023-07-11 09:07 UTC, llshang commented
@harry900831 感謝 Review，我會在這幾週修改好，到時再麻煩你再次確認。

2023-07-11 09:10 UTC, harry900831 commented on src/DP/aliens.md
> +不過，若是函數 \\(f\\) 是一凹函數（Concave function），又或是說在該函數上的每一點之切線斜率非嚴格遞減或遞增，我們便可以應用 Aliens 優化的技巧來解決此問題。
應該是我自己看錯 Sorry

2023-07-11 09:12 UTC, harry900831 commented
順便提一下，事實上這個技巧在國外也有人提出來，例如：https://codeforces.com/blog/entry/49691

你可以多看一些 codeforces 上的討論。

2023-08-23 16:18 UTC, harry900831 commented
friendly ping

2023-08-25 15:56 UTC, harry900831 commented
why are you closing this?

2023-08-25 16:09 UTC, llshang commented
> why are you closing this?

I accidentally closed this while resolving conflicts. I'll reopen it after completing the modifications in the next few days. Thanks.

2023-09-06 11:48 UTC, llshang commented
@harry900831 
I have made the modifications. Thanks for the review.

2025-08-28 04:08 UTC, closed without merging