add persistable_segment_tree.md
NTHU-CP/NTHU-CPP pull request #71
Opened 2023-05-14 13:03 UTC by valderyaya

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [x] Rebase to the latest main branch.
- [x] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-05-14 13:05 UTC, valderyaya commented
latex語法待改

2023-06-19 14:20 UTC, valderyaya commented
Finish

2023-06-20 06:09 UTC, valderyaya commented
@harry900831  Waiting review

2023-07-10 15:22 UTC, harry900831 requested changes
- There's a lot of space for improvement on this article.
- Please read more online resources instead of only reading something like OI-wiki, CSDN blog....
- The explanation is not clear, the code need to refactor, the format is incorrect, .... Please re-organize the whole article
- You may refer to others PR or the article that has been merged into NTHU-CPP to know that what kind of article you have to write.
- There's some application for persistent segment tree, If possible, you should also mention it. For example: https://codeforces.com/blog/entry/64628
- Please fix markdownlint and textlint.
- **You should better put more effort on this** otherwise it might not be merged into NTHU-CPP in the summer vacation.

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +有一點要注意的是，持久化線段樹需要使用動態開點來實作，如果使用僞指標的話就要特別注意一下記憶體的大小，如果有 \\(n\\) 次修改，那每次修改需要增加 \\(\lceil log_2{n} \rceil + 1\\) 個點，線段樹總空間會到 \\(2n -1 + n(\lceil log_2{n} \rceil + 1)\\)。 依照題目大小帶入數字 \\(n \leq 2\times10^5
你需要更詳細的解釋時間與空間複雜度

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +附上 [洛谷 P3834](https://www.luogu.com.cn/problem/P3834) 的code
Please use the online judge that we usually use, such as CSES, atcoder, CF.

Here's a problem for you : https://cses.fi/problemset/task/1737

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +```
Please wrap the segment tree as a struct

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +\\(0 \leq P \lt N\\)
Please follow the format:
https://nthu-cp.github.io/NTHU-CPP/sqrt/sqrt_decomposition.html

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +
Why the coding style are different in the whole article?

Please use your own code....

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +
Please remove the useless Marco and your personal habit on the code....

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +附上 [洛谷 P3834](https://www.luogu.com.cn/problem/P3834) 的code
對於真的找不到好 OJ但是又是很經典的題目 例如區間地k小 才考慮使用冷門OJ

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +\\(1\le n,m \le 10^5\\)， 點權在 \\([1,2^{31}-1]\\) 之間。
You use a lot of problem from 洛谷 but I believe there should also have lots of problem that can be solved by persistent segment tree on codeforces or atcoder

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +https://codeforces.com/problemset/problem/1771/F
Please use bullet list, problem shouldn't be list on the references.

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +https://oi-wiki.org/ds/persistent-seg/
If you only read the above two resources, it's pretty obvious that you have to do more research...

- https://usaco.guide/adv/persistent?lang=cpp
- https://cp-algorithms.com/data_structures/segment_tree.html#preserving-the-history-of-its-values-persistent-segment-tree
- https://codeforces.com/blog/entry/49777
- https://codeforces.com/blog/entry/56880

2023-07-10 15:22 UTC, harry900831 commented on src/data_structures/persistable_segment_tree.md
> +附上 [洛谷 P3834](https://www.luogu.com.cn/problem/P3834) 的code
In my opinion, https://www.spoj.com/problems/MKTHNUM/ SPOJ is better than 落谷

2023-07-17 05:17 UTC, closed without merging

2023-07-17 19:43 UTC, harry900831 commented
why are you closing this?

@valderyaya

2023-07-17 21:22 UTC, valderyaya commented
> why are you closing this?
> 
> @valderyaya 

我在修改的時候可能不小心按到了什麽，我再試著改回來

2023-07-18 09:44 UTC, valderyaya commented
@harry900831 我在pull rebase的時候遇到了一些問題，所以我把branch刪掉重建了，這導致了pull request被close，好像沒辦法restore，我可以修改完之後再新開一個pull request嗎