[:hammer:] add chapter AP, Bridge & BCC
NTHU-CP/NTHU-CPP pull request #73
Opened 2023-05-14 13:50 UTC by Lotanie

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [ ] Rebase to the latest main branch.
- [ ] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [ ] Review the content by myself.
- [ ] Pass tests/CI.

2023-06-04 10:47 UTC, Lotanie commented
@harry900831 想請助教幫忙看看大綱與文章架構(題解的部分還在進行中)

2023-06-05 07:27 UTC, harry900831 requested changes
- Move BCC to another md file
- please provide template code
- please add an example problem with detail explanation that can be solve by bridge/ap, BCC after you intro the respective topic.
- For the last problem section, you only need to hint the user how to solve it
- Please re-request review after you finish it.

2023-06-05 07:27 UTC, harry900831 commented on src/SUMMARY.md
> +- [Graph]()
move this section above to the place that under dynamic programming

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +在無向圖上做 DFS tree 時要注意的是: 無向圖的 DFS 會讓一條邊被看到 2 次。如果你的 code 寫的是看到一條邊就根據它是 tree edge/back edge 做事，那你有可能做了重複的操作而導致 WA。
提到看到兩遍是好事
但不太懂後面寫重複操作而WA

你可以舉例子 或是直接刪掉那句話

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +```
不太懂 
在有像圖 就只會有 tree edge and back edge 你這邊看起來還是用 無像圖做例子 
這兩份code沒差吧？

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +### 觀察 for AP
這標題怪怪的

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +### 觀察 for Bridge
這標題怪怪的

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +```
在包裝得更模板一點

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +## Using DFS tree for Bridge/AP
for -> to find

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +### 如何修改
Need more explanation

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +BCC 指的是沒有 Bridge 的 Connected Component，在中文常稱之為邊雙連通分量、橋連通分量。例如下圖我們能找到兩個 BCC
怎麼又是一樣的BCC

你可以分一下 BCC-Vertex and BCC-Edge

2023-06-05 07:27 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge_BCC.md
> +
need more explanation

2023-06-15 18:59 UTC, Lotanie commented
@harry900831 助教好，我修改了助教提到的問題並補完了題目相關的部分，想請助教幫忙 review，謝謝助教!

2023-06-16 06:32 UTC, harry900831 requested changes
- Overall, LGTM
- No space in filename and directory name, please fix it.
- Please fix textlint
- I might merge it after your next revision, please check the whole article by yourself in advance.

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +    vector<pair<int, int> > get_bridge() {
vector<pair<int, int>> is fine.
After C++11, you don't have to add additional space between >>, please fix it.

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +## Using DFS tree for Bridge/AP
Use DFS Tree to get Bridge/AP

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +## Using DFS tree for Bridge/AP
Get Bridge/AP by DFS tree

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +所以，如果我們每遇到一條 back edge \\( (u,v) \\)，就把樹上 \\(u \\) 到 \\( v \\) 的路徑都標記成不是 bridge，那麼最後那些沒被標記到的邊就會是 bridge。問題是，**我們要如何快速標記一條路徑上所有的邊？**
沒被標記的點一定是 bridge 嗎？一兩句話解釋一下。

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +### 前綴和 -> 子樹標記總和
前綴和->路徑和？

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +    vector<pair<int, int> > get_bridge() {
Ditto

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +        G[v].emplace_back(u);
Do you test the correctness of the code?

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +        G.assign(n+1, vector<int>());
Do you test the correctness of the code?

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +>[Codeforce - Two Fairs](https://codeforces.com/contest/1259/problem/E)
Problem size

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +>[Codeforces - Bertown roads](https://codeforces.com/contest/118/problem/E)
Problem size

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +>[Uva - Mining Your Own Business](https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=246&page=show_problem&problem=3549)
Problem size

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +> 給一張 \\( N \\) 個點 \\( M \\) 條邊的帶權無向圖與兩點 \\(S \\) , \\(T \\)，要你選至多兩條邊刪除後使 \\(S \\) , \\(T \\) 不連通。要求選的邊權重和最小。\\( N \leq 1000, M \leq 30000 \\)
There should be an empty line between the statement and the problem size.

2023-06-16 06:32 UTC, harry900831 commented on src/SUMMARY.md
> +  - [BCC](graph/introduction_to_BCC.md)
BCC-Vertex and BCC-Edge

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +# AP, Bridge
rename this too

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +# BCC
rename this too

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +- 把每個 BCC-Vertex 縮成一個點，他周圍的點會是這個 BCC-Vertex 中的 AP。
每一點都需要一兩句話稍微解釋一下

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +- 把每個 BCC-Vertex 縮成一個點，他周圍的點會是這個 BCC-Vertex 中的 AP。
> 把每個 BCC-Vertex 縮成一個點，他周圍的點會是這個 BCC-Vertex 中的 AP。

這句話看不懂

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +例如下圖中，\\( A \\) 通過 DFS 可以找到 \\( B,C,D \\)，這四點恰為一個 BCC-Vertex。\\( A \\) 點不會找到 \\( E \\)，因為 \\( D \\) 點是 AP，不會繼續 DFS 下去。而 \\ (D \\) 點會檢查到 \\ (E \\) 是 AP，因此 \\(D,E\\) 會是一個 BCC-Vertex。
Render error

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +>給定一張 \\( N \\) 個點 \\( M \\) 條邊的無向圖，問那些邊剛好位於一個簡單環上。
Problem size

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +                    bcc.back().emplace_back(x);
Wrap it as a struct such as:
https://github.com/OmeletWithoutEgg/ckiseki/blob/master/codes/Graph/BCC_Vertex.cpp

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +- 如果把每個 BCC-Edge 縮成一個點，那麼新得到的圖會是一棵樹或者森林。
Ditto, 需要幾句話解釋一下

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +            x = stk.top(); stk.pop();
Ditto

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +> 請有興趣的讀者自行去連結查看題目敘述，以免暴雷未來打算模擬這場比賽當作團練的人。
這不是台北站 應該可以放題目敘述

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +>[TIOJ - 圓桌武士](https://tioj.ck.tp.edu.tw/problems/1684)
Problem size

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +>[Codeforces - Tourist Reform](https://codeforces.com/contest/732/problem/F)
Problem size

2023-06-16 06:32 UTC, harry900831 commented on src/graph/introduction_to_BCC.md
> +> [POJ - Road Construction](http://poj.org/problem?id=3352)
Problem size

2023-06-16 06:44 UTC, Lotanie commented on src/graph/introduction_to_AP_bridge.md
> +        G[v].emplace_back(u);
Yes

2023-06-16 06:44 UTC, Lotanie commented on src/graph/introduction_to_AP_bridge.md
> +        G.assign(n+1, vector<int>());
Yes

2023-06-17 08:21 UTC, Lotanie commented on src/graph/introduction_to_AP_bridge.md
> +但 root 是沒有祖先的，因此 root 我們要拉出來特別判斷。很明顯，當 root 有至少兩棵子樹的時候，root 一定會是 AP，否則就不是。
想問這部分是不是可以放在 DFS tree 的章節一起講，然後這邊就只要簡單提到說我們在 DFS tree 有說明過為何不會有橫跨子樹的 edge 這樣？

2023-06-17 08:24 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +但 root 是沒有祖先的，因此 root 我們要拉出來特別判斷。很明顯，當 root 有至少兩棵子樹的時候，root 一定會是 AP，否則就不是。
其實我有在想，你這邊介紹滿多DFS Tree，感覺幾乎快把DFS Tree的內容講完了。理想上感覺應該是把你前半部分DFS Tree 的內容移到 DFS_Tree.md ，並補全DFS Tree的章節，不過我不會要求你這樣做(如果你願意我會很開心，不一定要在這次PR做)。

2023-06-17 08:26 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +但 root 是沒有祖先的，因此 root 我們要拉出來特別判斷。很明顯，當 root 有至少兩棵子樹的時候，root 一定會是 AP，否則就不是。
那你這邊就一兩句話提一下說不會有橫跨子樹的 edge，讀者可以簡單想一下，那條 edge一定會變成tree edge 之類的

2023-06-17 17:43 UTC, Lotanie commented
@harry900831 助教好，我修改了助教所提到的問題，想請助教幫忙 review，謝謝助教!

2023-06-18 11:23 UTC, harry900831 requested changes
LGTM, I'll merge it after your revision.

2023-06-18 11:23 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +            DFS(v);//u->v 為 tree edge
move the comment above this line

2023-06-18 11:23 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +    color[u] = 2;
// 和註解文字 要空一個空白

2023-06-18 11:23 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +    color[u] = 2;
請針對這對所有做修正

2023-06-18 11:23 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +<img src="image/AP_and_Bridge/Root_AP_Observation.JPG" width="400" style="display:block; margin: 0 auto;"/>
圖片上不要有字體很醜的中文 可以改英文

2023-06-18 11:23 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +<img src="image/AP_and_Bridge/General AP.JPG" width="400" style="display:block; margin: 0 auto;"/>
render error

2023-06-18 11:23 UTC, harry900831 commented on src/graph/introduction_to_AP_bridge.md
> +- \\((v\ 的子樹標記總和)\\) \\(-\\) \\((\\)這顆子樹在 \\( v \\) 結束的 back edge 數量\\()\\)。
why 前半部份要包在mathjax內？

2023-06-18 13:17 UTC, Lotanie commented
@harry900831 助教好，我修改了助教所提到的問題，想請助教幫忙 review，謝謝助教!

2023-06-18 14:46 UTC, merged

2023-06-18 14:46 UTC, harry900831 commented
Thanks for your contribution!