Add convex hull trick draft
NTHU-CP/NTHU-CPP pull request #74
Opened 2023-05-14 14:00 UTC by aftermaaath

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [x] Rebase to the latest main branch.
- [ ] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-05-21 14:18 UTC, aftermaaath commented
I would fix the workflow right after I put all solutions for exercises. The outline and most of the content is finished, except for the images, the solutions & problem descriptions for the exercises, and the summary. I think I can ask for comments first so I can fix the content earlier. Thanks.

@harry900831

2023-05-22 17:22 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +以下是用此方法解 [CSES - Monster Game I](https://cses.fi/problemset/task/2084/) 的範例 code。
同時 CSES - monster Game I 的轉移是有點太簡單，可以的話看是要不要就這個新題 或是額外再這邊再講解一個要推一下子才能推出 ax+b 的形式的題目。

2023-05-22 17:24 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +題目大致與 [CSES - Monster Game I](https://cses.fi/problemset/task/2084/) 相同，但此題不再保證 \\(f\\) 與 \\(s\\) 的單調性，意即斜率與查詢都不再單調。不過透過 CDQ 分治，我們可以「人為」創造出斜率的單調性。
一樣需要推一下遞迴式

2023-05-22 17:25 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +我們一樣要在遞迴過程中，將序列分左半邊與右半邊處理。前面提到我們想創造出斜率的單調性，因此在遞迴過程中我們要維護一個斜率單調的序列，且裡面沒有不會被取到的直線。先不論直線如何計算，討論維護的部分。維護的方式類似 merge sort 的過程，只是要注意新增直線到序列尾端時，一樣要做 pop 的動作，將不可能會被取到的直線刪除。
要遞迴什麼？ 這部分需要更詳細說明，我看過去看不太懂。

2023-05-22 17:49 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +// 希望這一part可以日後再補Q
我其實不太懂這裡的動態凸包是指什麼，不過應該要提到維護插入線段查詢x的最高點是有模板可用的，可參考：https://robert1003.github.io/2020/02/17/dp-opt-convex-hull-trick.html#convex-hull-trick-cht


大家的codebook大概都會備一份

2023-05-22 17:50 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +// 希望這一part可以日後再補Q
可以的話底下可以挑個別人的模板或自己寫一個，然後後面的 excercise 就依靠那個模板來解。

2023-05-22 17:53 UTC, harry900831 commented
Furthermore, you could provide some comments about the references about which on is recommended to read, and hint the reader which resources is good for them if they want to learn more.

2023-05-23 02:16 UTC, aftermaaath commented on src/dp/convex_hull_optimization.md
> +以下是用此方法解 [CSES - Monster Game I](https://cses.fi/problemset/task/2084/) 的範例 code。
查詢不單調的範例，我原本也想找個新題，找很久找不到才先參考其他 tutorial 這樣寫Q，我找到題目後會將這部分更新。

Exercise 的題目會有更複雜的轉移，這樣還需要再講解一個嗎？（或是我可以直接搬上來？exercise 也會有題解）

2023-05-23 02:20 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +以下是用此方法解 [CSES - Monster Game I](https://cses.fi/problemset/task/2084/) 的範例 code。
放在這部分的題目都需要「詳細」的題解，包含轉移是怎麼推以及實作細節，因此我認為在這邊需要再放一題難一點的。

Exercise 的目的是提供讀者練習的題目，因此他的解釋不需要太完整，除非是網路上都找不到解答而他又很難的話。

2023-06-16 19:02 UTC, harry900831 requested changes
- The content overall LGTM!
- Please refactor your code
- I might merge it after your revision so please check the whole article again by yourself
- Please re-request review after you finish it

Thanks

2023-06-16 19:10 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +CDQ 分治的過程就是對於一個序列 \\([l, r]\\)，我們先遞迴解決 \\([l, mid]\\) 的子問題，再處理 \\([l, mid]\\) 對 \\([mid + 1, r]\\) 的貢獻，最後再遞迴處理 \\([mid + 1, r]\\)。
我先在覺得斜率優化用CDQ分治的教學好像應該在 #63 裡面詳細講才對，但是你寫的整體來說還不錯，看要不要修改一下然後整塊搬運過去給 #63。

@chyyen @aftermaaath 你們有什麼想法嗎？

2023-06-18 00:40 UTC, aftermaaath commented on src/dp/convex_hull_optimization.md
> +CDQ 分治的過程就是對於一個序列 \\([l, r]\\)，我們先遞迴解決 \\([l, mid]\\) 的子問題，再處理 \\([l, mid]\\) 對 \\([mid + 1, r]\\) 的貢獻，最後再遞迴處理 \\([mid + 1, r]\\)。
Hmm 我其實覺得都可，當初是參考 OI wiki 才寫在這邊，可能看看 CDQ 那裡的架構如何，我沒有太大的意見。

2023-06-19 02:48 UTC, chyyen commented on src/dp/convex_hull_optimization.md
> +CDQ 分治的過程就是對於一個序列 \\([l, r]\\)，我們先遞迴解決 \\([l, mid]\\) 的子問題，再處理 \\([l, mid]\\) 對 \\([mid + 1, r]\\) 的貢獻，最後再遞迴處理 \\([mid + 1, r]\\)。
我也覺得 ok

2023-06-23 17:26 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +CDQ 分治的過程就是對於一個序列 \\([l, r]\\)，我們先遞迴解決 \\([l, mid]\\) 的子問題，再處理 \\([l, mid]\\) 對 \\([mid + 1, r]\\) 的貢獻，最後再遞迴處理 \\([mid + 1, r]\\)。
所以這部分就交給 @chyyen 寫囉

2023-08-07 01:46 UTC, aftermaaath commented on src/dp/convex_hull_optimization.md
> +    注意到在綠色線被移除之前，藍色線都不可能提供答案。因此我們要多判斷的是藍色線在綠色線被移除之後，會不會成為可能的轉移來源。具體而言，在我們放入紅色線前，要決定藍色線是否要被移除，而方法是多判斷在綠色線被 pop 時的那一個查詢，藍色線會不會提供比紅色線更好的答案。
I think our approach is the same, and also I think it is correct (not proved by AC). Should I mention this link still?

2023-08-08 04:44 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +CDQ 分治的過程就是對於一個序列 \\([l, r]\\)，我們先遞迴解決 \\([l, mid]\\) 的子問題，再處理 \\([l, mid]\\) 對 \\([mid + 1, r]\\) 的貢獻，最後再遞迴處理 \\([mid + 1, r]\\)。
可以一句話提一下 可以使用 CDQ 分治

2023-08-08 04:44 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +    注意到在綠色線被移除之前，藍色線都不可能提供答案。因此我們要多判斷的是藍色線在綠色線被移除之後，會不會成為可能的轉移來源。具體而言，在我們放入紅色線前，要決定藍色線是否要被移除，而方法是多判斷在綠色線被 pop 時的那一個查詢，藍色線會不會提供比紅色線更好的答案。
If the approach is the same, then never mind.

2023-08-30 10:36 UTC, fffelix-huang requested changes
Great content!
- Please fix minor errors
- Fix textlint
- Re-request review after you finish it
Thanks~

2023-08-30 10:36 UTC, fffelix-huang commented on src/dp/convex_hull_optimization.md
> +先將所有貓的 \\(t_i\\) 減掉 \\(h_1\\) 至 \\(h_i\\) 的距離，這樣就可以得到每隻貓最早能被接走時，feeder 的出發時間。
上面沒有提到 $h_i$

2023-08-30 13:23 UTC, harry900831 requested changes

2023-08-30 13:23 UTC, harry900831 commented on src/SUMMARY.md
> +  - [Convex hull optimization](dp/convex_hull_optimization.md)
Convex Hull Optimization

2023-08-30 13:26 UTC, harry900831 commented on src/dp/convex_hull_optimization.md
> +CDQ 分治的過程就是對於一個序列 \\([l, r]\\)，我們先遞迴解決 \\([l, mid]\\) 的子問題，再處理 \\([l, mid]\\) 對 \\([mid + 1, r]\\) 的貢獻，最後再遞迴處理 \\([mid + 1, r]\\)。
@aftermaaath So are you going to delete this part? Or you gonna remain the paragraph you wrote. Both are fine for me.

2023-08-30 14:53 UTC, merged