Add Monotone_optimization.md `draft`
NTHU-CP/NTHU-CPP pull request #76
Opened 2023-05-14 14:26 UTC by Cr-bubble

Add Monotone_optimization.md

- [x] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [ ] Rebase to the latest main branch.
- [x] List all the references.
- [x] Successfully build the website by mdBook with no error after the change.
- [x] Exclude any irrelevant files.
- [] Link to the issue which is related to your change.
- [x] Review the content by myself.
- [ ] Pass tests/CI.

2023-06-10 17:26 UTC, Cr-bubble commented
Hi @harry900831, the outline and most of the content is finished, except problem descriptions and solutions for the exercises. I will add them as soon as possible. I think I can ask for comments first so I can fix the content. Thanks.

2023-06-20 07:32 UTC, harry900831 requested changes
- 現在看下來這三個主題塞在同一篇內容會有點太多，同時對你完成這次作業來說也會有點太多，我覺得可以分成三篇1. 1D/1D單調 2. Knuth optimization 3. divide and conquer optimization。看你想要先 focus 在哪一篇我們先 merge 那一篇進去。
- 目前的大問題是 1. 解釋的不是很清楚，至少我看過去還是看不懂QQ 2. 要準備 teamplate code 3. 對於應用的題目需要證明他確實有這個單調性
- 每一個技巧希望都能詳細講解個兩題，題目最好使用 CF, Atcoder, CSES 等等真找不到的話再去用一些不常用的OJ
- 我的建議是多用圖片輔助解釋，但是圖片上也需要標示清楚，先專心將其中一個技巧講清楚就好，那就已經會花掉很多時間了。不要只針對我有 comment 的地方去修改。

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +- 凹單調淘汰點 \\((i,j)\\) 左上與右下的轉移點。
我的想法是先在圖上標出求 dp[j] 用到哪幾格

然後介紹凹單調性 並在圖中標示出他們有什麼樣子的關係

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +```
請注意程式碼 format 並避免使用自己特別的 coding  tyle 例如 signed main()

請使用你上方提供的teamplate 來解題

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +```
Ditto

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +> 則決策點具有單調性 ： \\(opt\[i][j-1]\le opt\[i][j]\le opt\[i+1][j]\\)，即 \\(dp\[i][j]\\) 的決策點位在 \\(dp\[i][j-1]\\) 到 \\(dp\[i+1][j]\\) 的決策點之間。
請使用 f(i, j) and opt(i, j)

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +- 觀察可發現代價函數 \\(C\\) 滿足 Monge condition (等號都成立)，可以套用 Knuth Optimization 解決。
需要證明

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +- **凸四邊形不等式** (convex Monge condition)：若 \\(A\\) 滿足凹四邊形不等式，則 \\(a+d\le c+b\\)
或者說 在這章節最後 在總結一次這個性質以及遇到這個性質之後可以怎麼做

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +- 對於任意 \\(i^{\prime}\lt i,j^{\prime}\lt j\\) 有 \\(B\[i]\[j^{\prime}]\lt B\[i^{\prime}]\[j^{\prime}]\\) (\\(\because B\[i]\[j]\lt B\[i^{\prime}]\[j]\\)，由凹單調的逆反命題得知)，因此所有位於 \\(B\[i][j]\\) 左上角的元素都不可能是最佳
誰的最佳轉移來源

2023-06-20 07:32 UTC, harry900831 commented on src/Dynamic_Programming/Monotone_optimization.md
> +            }
這 l, r 應該可以換成更有效率的做法

2023-08-10 08:15 UTC, closed without merging

2023-09-12 13:40 UTC, harry900831 requested changes

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +}
Ditto

移到上面

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +> 顯然 \\( w(a,c)+w(b,d) = w(a,d) + w(b,c),\\) \\(\forall a \le b \le c \le d\\)
為什麼要用 
\>
\>
\> 把這個內容包住

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +> 訪問樹中元素 \\(e_i\\) 的成本 \\(cost(e_i)\\) 為該元素到樹根的路徑邊數。給定各元素的查詢次數 \\(f(e_1), f(e_2), \dots , f(e_n)\\)，定義一顆二元搜尋樹的總成本是：> \\[f(e_1)*cost(e_1) + f(e_2)*cost(e_2) + \dots + f(e_n)*cost(e_n)\\]
\times instead of *

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +> <img src="image\Knuth_optimization\equal_explain.jpg" width="300" style="display:block; margin: 0 auto;"/>
why 

\>
\>
\>

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/image/Monotone_optimization/blank.JPG
You should remove useless figures

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
filename -> knuth_optimization.md

Same as the folder

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +
You may make this problem as an example instead of exercise.

The content is fine, just remove the <details> and change the format

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +\implies& x((i+j)/2+1) \ge x((i+j+1)/2) \\\\
you should put floor function in the statement

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +\implies& -x((i+j)/2+1) \le -x((i+j+1)/2) \\\\
這個證明我看起來覺得怪怪的

首先你其實只有打算證對於所有 i, j and i < j
他會符合 w(i,j)+w(i+1,j+1)≤w(i+1,j)+w(i,j+1)
你並沒有證明對於任意 a, b, c, d

再來就是你反證法的敘述我看起來很怪

邏輯應該要是你要證明
對於所有 i, j and i < j, w(i,j)+w(i+1,j+1)≤w(i+1,j)+w(i,j+1)
反證法 假設這件事情不對
因此存在一組 i, j 使得w(i,j)+w(i+1,j+1) "≥" w(i+1,j)+w(i,j+1)

然後推推推，推到最後發現x((i+j)/2+1)≤x((i+j+1)/2) 矛盾了
故得證

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +> 則 \\(opt(i,j-1) \le opt(i,j) \le opt(i+1,j) \\)。
這一部分有點亂 同樣的 statement 你寫了兩次

我想像中的敘述流程會是

1. 介紹四邊形不等式
2. 介紹 opt 
3. 介紹 Knuth optimization 他是 .....
4. 接著開始證明為什麼 w(i, j) 滿足那些條件 opt 就會有那個性質

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +Knuth's Optimization 告訴我們，當 DP 的代價函數 \\(w\\) 滿足**四邊形不等式**與**區間單調性**時，DP 的轉移來源會有單調性，可以藉此加速 DP。
IIUC
> Knuth's optimization
>
> 若代價函數 \\( w(i,j) \\) 滿足
>
> - 令 \\( a\le b\le c\le d \\)
> - 區間單調性：\\( w(b,c) \le w(a,d) \\) 
> - 凸四邊形不等式：\\( w(a,c) + w(b,d) \le w(a,d) + w(b,c)\\)
>
> 則對於此轉移式子 dp(i,j) = w(i,j) + \underset{i\le k\lt j}{min} \\{dp(i,k)+dp(k+1,j)\
> 其轉移點 \\(opt(i,j-1) \le opt(i,j) \le opt(i+1,j) \\)。

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +有興趣的讀者可以參考這篇 [Efficient Dynamic Programming Using Quadrangle Inequalities](https://dl.acm.org/doi/pdf/10.1145/800141.804691)
這裡我就整段看不懂了QQQ

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +</details>
這種如果是證明過程中 refer 出去的不需要用 \<details> 包起來
不過你 refer 到論文有點@@

我會建議如果不難的話 至少用個幾句話給個淺顯的證明 或是提供一些直覺上會對的想法

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +opt_{i-2,j-3} \le opt_{i-2,j-2} \le opt_{i-1,j-2}\\\\
既然 i - j = 0 代表 i  == j 那 opt(i - 2, j - 3) 真的存在嗎？這是一個右界小於左界的case?

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +以下為程式碼片段
這一段也看不懂QQ

我懂覺得你的圖與你的敘述講得很像是在算某一條斜排的值上的每個元素只會使用到它左邊和下面的元素

但事實上其實是要 iterate from opt 表格上 他左邊的值 to opt 表格上他下面的值

2023-09-12 13:40 UTC, harry900831 commented on src/Dynamic_Programming/Knuth_optimization.md
> +\\[ 計算每塊綠色格子只需左邊與下方黃色格子的 opt\\]
完全會被這句話帶歪