Add LCA
NTHU-CP/NTHU-CPP pull request #94
Opened 2023-06-27 04:30 UTC by didwhddks

- [ ] Read [Contribute to NTHU-CPP](https://nthu-cp.github.io/NTHU-CPP/others/contribution.html).
- [ ] Rebase to the latest main branch.
- [ ] List all the references.
- [ ] Successfully build the website by mdBook with no error after the change.
- [ ] Exclude any irrelevant files.
- [ ] Link to the issue which is related to your change.
- [ ] Review the content by myself.
- [ ] Pass tests/CI.

2023-06-27 04:40 UTC, didwhddks commented
@harry900831 助教好，我已經完成所有的 requested changes，想請你幫我 review 一下。另外因為我不太熟悉 git 的操作，搞砸了 commit history，所以我關閉了先前的 PR 並重新發了一次。

2023-06-27 11:57 UTC, harry900831 requested changes
I'm thinking about whether wrapping the implementation to a struct object is a good idea, such as: https://github.com/OmeletWithoutEgg/ckiseki/blob/master/codes/Graph/BCC.cpp.
Therefore others may easily copy it to their codebook and having a better readability compare to reading lambda code.
 
 I'm thinking about the following two interface:
 
 1. Pass the graph to construct the lca object.
```cpp
struct LCA {
...
  LCA(vector<vector<int>>& g, int n);
  int lca(int u, int v);
  vector<vector<int>> ancestor;
};
```
2. store the graph inside lca object
```cpp
struct LCA {
...
  LCA(int n);
  int lca(int u, int v);
  void add_edge(int u, int v);
  vector<vector<int>> ancestor;
  vector<vector<int>> g;
};
```

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +
對於DFS 走訪到的點 u

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +- 遞迴 return 後檢查所有包含點 \\( u \\) 在內的查詢點對，如果另一點為搜索過的狀態，那麼根據 Tarjan 的想法，此時我們可以知道該查詢點對的最近共同祖先為另一點所在集合的最高點。
子樹們的集合要與點 u 合併？

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +- 遞迴 return 後檢查所有包含點 \\( u \\) 在內的查詢點對，如果另一點為搜索過的狀態，那麼根據 Tarjan 的想法，此時我們可以知道該查詢點對的最近共同祖先為另一點所在集合的最高點。
若另一個點 還沒被檢查到怎麼辦？

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +此小節主要關注於如何利用樹重鏈剖分的概念來查詢點對的最近共同祖先，如果讀者對於樹重鏈的定義以及其相關操作（跳輕邊）還不太清楚的話，建議可以先去觀看相關章節。
樹重練剖分 -> 樹練剖分

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +結合上述資訊可知，點 \\( i \\) 為點 \\( u \\) 和點 \\( v \\) 的共同祖先且點 \\( u \\) 和點 \\( v \\) 會在點 \\( i \\) 的不同子樹內，否則點 \\( u \\) 和點 \\( v \\) 在跳上來當前重鏈之前就會在同一重鏈上。因此對於 Case 2，可知點 \\( i \\) 會是點對 \\( (u,\ v) \\) 的最近共同祖先
透過不斷跳輕邊直到調整到同一重鏈上的正確性說明不夠完整

還是你覺得這邊不需要好好證明，這應該是樹練剖分章節該證明的？

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +有了上述預處理好的陣列後，剩下的工作就會是處理 RMQ 問題。對於 RMQ 問題，有許多經典的解法像是線段樹、序列分塊或是 Sparse Table，這邊我們不會細講這些經典解法的概念和實作細節，有興趣的讀者可以去觀看相關的章節。而此小節我們主要關注於如何利用高度分塊來達到 \\( O(N) \\) 預處理、每次查詢 \\( O(1) \\) 的做法。
...如何利用對歐拉路徑的陣列分塊....

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +觀察 Depth 陣列我們可以發現，陣列中相鄰的值會剛好差 1。原因是因為在建立歐拉路徑時，我們每次只會往上或是往下走一步，所以在歐拉路徑陣列中相鄰的點，點深度會剛好差 1。基於此特性，我們可以用來優化區間最小值的查詢。
觀察歐拉路進的陣列的每個元素的深度

2023-06-27 11:57 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +- 區間 \\( [1,\ 3] \\) 的最小值均對應到 index \\( 1 \\)
這一個舉例看不太懂

2023-06-29 13:15 UTC, didwhddks commented on src/graph/lowest_common_ancestor.md
> +結合上述資訊可知，點 \\( i \\) 為點 \\( u \\) 和點 \\( v \\) 的共同祖先且點 \\( u \\) 和點 \\( v \\) 會在點 \\( i \\) 的不同子樹內，否則點 \\( u \\) 和點 \\( v \\) 在跳上來當前重鏈之前就會在同一重鏈上。因此對於 Case 2，可知點 \\( i \\) 會是點對 \\( (u,\ v) \\) 的最近共同祖先
我是想說關於樹鏈剖分相關操作的正確性以及時間複雜度都會在相關章節被證明，所以這邊就沒有過多著墨。

2023-06-29 13:16 UTC, harry900831 commented on src/graph/lowest_common_ancestor.md
> +結合上述資訊可知，點 \\( i \\) 為點 \\( u \\) 和點 \\( v \\) 的共同祖先且點 \\( u \\) 和點 \\( v \\) 會在點 \\( i \\) 的不同子樹內，否則點 \\( u \\) 和點 \\( v \\) 在跳上來當前重鏈之前就會在同一重鏈上。因此對於 Case 2，可知點 \\( i \\) 會是點對 \\( (u,\ v) \\) 的最近共同祖先
Got it

2023-06-29 18:01 UTC, harry900831 commented on src/graph/lca.md
> +          ~ancestor[u][i - 1] ? ancestor[ancestor[u][i - 1]][i - 1] : -1;
If you store the vertex by 1-based, and 0 as -1 over here, then you don't have to do this kind of ?:.

I would prefer to refactor to 1-based.

2023-06-29 18:17 UTC, harry900831 commented on src/graph/lca.md
> +                     : mx[u][i - 1];
Ditto

2023-06-29 18:18 UTC, harry900831 commented on src/graph/lca.md
> +  }
to 1-based index

2023-06-29 18:19 UTC, harry900831 commented on src/graph/lca.md
> +struct LCA {
If you store the vertex by 1-based, and 0 as -1 over here, then you don't have to do this kind of ?:.

I would prefer to refactor to 1-based.

2023-06-30 08:52 UTC, harry900831 approved these changes

2023-06-30 08:52 UTC, merged